# -*- coding: utf-8 -*-
"""初等数学知识体系：500个知识点，涵盖初中高中全部数学内容。"""
from content_bank import T

ELEMENTARY_MATH = [
  {"ch":"第一章","title":"数与式子计算","en":"NUMBERS & ALGEBRAIC EXPRESSIONS","sub":"实数运算 · 指数对数 · 三角函数 · 式与方程 · 不等式","desc":"从实数系到代数式、方程与不等式，构建初等代数的完整运算体系。","sections":[
    {"name":"1.1 实数系与运算律","color":"#2563eb","desc":"实数、绝对值、运算律","topics":[
      T("自然数", formula=r"\mathbb{N}=\{0,1,2,\dots\}", explain="自然数是计数的基础，包括0和正整数。在数论中有时不含0。", deriv="由皮亚诺公理严格定义：0是自然数，每个自然数n有唯一后继n+1，归纳公理成立。", app="计数、排序、归纳法的基础。", note="不同教材对0是否属于自然数有不同约定。", hist="皮亚诺1889年给出公理系统。", ext="推广到序数和基数。"),
      T("整数", formula=r"\mathbb{Z}=\{\dots,-2,-1,0,1,2,\dots\}", explain="整数是自然数及其相反数构成的集合，对加减乘封闭。", deriv="在自然数集上添加负元，使减法封闭。", app="表示盈亏、温度、方向等具有相反意义的量。", note="整数集是环（对加减乘封闭，除法不封闭）。", hist="负数在公元7世纪由印度数学家引入。", ext="模n剩余类环。"),
      T("有理数", formula=r"\mathbb{Q}=\{\frac{p}{q}\mid p,q\in\mathbb{Z}, q\neq 0\}", explain="有理数是可表为两个整数之比的数，包括整数和分数。", deriv="在整数环上构造分式域得到。", app="实际测量中的有限小数和循环小数。", note="有理数集可数（可与自然数一一对应）。", hist="古希腊毕达哥拉斯学派认为万物皆数（有理数）。", ext="p进数是有理数的另一种完备化。"),
      T("无理数", explain="不能表为两个整数之比的实数，即无限不循环小数。", deriv="证明√2是无理数：设√2=p/q，推出p,q均为偶数，与既约矛盾。", app="√2, π, e等。", note="无理数集不可数，比有理数多得多。", hist="公元前5世纪希帕索斯发现√2不可公度，动摇毕达哥拉斯学派。", ext="代数数与超越数的分类。"),
      T("实数系", formula=r"\mathbb{R}", explain="有理数与无理数的并集，构成完备有序域。", deriv="由有理数经戴德金分割或柯西序列完备化得到。", app="微积分与数学分析的基础数域。", note="实数不可数但可定义，具有完备性（确界原理）。", hist="19世纪戴德金、康托尔、魏尔斯特拉斯分别给出严格构造。", ext="实数的完备性等价于确界原理、单调有界定理、区间套定理、有限覆盖定理、柯西收敛准则。"),
      T("数轴", explain="规定了原点、正方向和单位长度的直线，实数与数轴上的点一一对应。", deriv="利用实数的有序性和稠密性建立对应。", app="几何直观表示实数，比较大小。", note="稠密性：任意两个实数之间存在无穷多个实数。", hist="笛卡尔创立解析几何时数与形结合。", ext="推广到复平面和n维欧氏空间。"),
      T("相反数", formula="a+(-a)=0", explain="实数a的相反数是-a，满足a+(-a)=0。", deriv="由加法逆元的存在性定义。", app="化简符号、去括号。", note="0的相反数是0；互为相反数的两数和为0。", hist="负数概念确立后自然产生。", ext="在抽象代数中即加法群的逆元。"),
      T("绝对值", formula=r"|a|=\begin{cases}a, & a\geq 0 \\ -a, & a<0\end{cases}", explain="实数a的绝对值是数轴上表示a的点到原点的距离。", deriv="由距离定义导出分段表达式。", app="距离度量、误差分析、不等式估计。", note="|a-b|表示a,b两点间的距离；|a|≥0，等号当且仅当a=0。", hist="分析学中描述邻域和极限的基础工具。", ext="推广到向量的模、范数。"),
      T("倒数", formula=r"a\cdot\frac{1}{a}=1\ (a\neq 0)", explain="非零实数a的倒数是1/a，满足a·(1/a)=1。", deriv="由乘法逆元的存在性定义。", app="除法转化为乘法、解方程。", note="0没有倒数；倒数等于本身的数是±1。", hist="分数运算的基础。", ext="域中每个非零元有乘法逆元。"),
      T("加法交换律", formula="a+b=b+a", explain="两个数相加，交换加数位置，和不变。", deriv="由实数域的公理直接给出。", app="简化加法运算、凑整。", note="在矩阵乘法中不成立。", hist="运算基本性质。", ext="交换群（阿贝尔群）的定义特征。"),
      T("加法结合律", formula="(a+b)+c=a+(b+c)", explain="三个数相加，先把前两个相加或先把后两个相加，和不变。", deriv="实数域公理。", app="灵活结合凑整简化计算。", note="保证连加结果唯一。", hist="运算基本性质。", ext="半群只需结合律，不需要交换律。"),
      T("乘法交换律", formula="ab=ba", explain="两个数相乘，交换因数位置，积不变。", deriv="实数域公理。", app="简化乘法、约分。", note="矩阵乘法、向量叉乘不满足交换律。", hist="运算基本性质。", ext="非交换代数的研究对象。"),
      T("乘法结合律", formula="(ab)c=a(bc)", explain="三个数相乘，先乘前两个或先乘后两个，积不变。", deriv="实数域公理。", app="灵活结合凑整简化计算。", note="保证连乘结果唯一。", hist="运算基本性质。", ext="结合代数的基础。"),
      T("分配律", formula="a(b+c)=ab+ac", explain="一个数乘两个数的和，等于这个数分别乘这两个数再相加。", deriv="实数域公理，连接加法与乘法。", app="整式乘法、因式分解、简便运算。", note="是连接加法和乘法的唯一桥梁。", hist="运算基本性质。", ext="环的定义特征之一。"),
      T("实数大小比较", explain="数轴上右边的数总比左边的大；正数>0>负数。", deriv="利用有序域的序关系。", app="比较大小、解不等式。", note="|a|>|b|等价于a²>b²（对实数成立）。", hist="有序域的基本性质。", ext="复数没有自然的大小关系。"),
      T("科学记数法", formula=r"a\times 10^n\ (1\leq|a|<10)", explain="把一个数写成a×10ⁿ的形式，其中1≤|a|<10。", deriv="利用10的幂次缩放。", app="表示极大或极小数，如光速3×10⁸m/s。", note="n为整数，确定n的方法是数小数点移动位数。", hist="科学计算中标准化表示。", ext="浮点表示法的原型。"),
      T("有效数字", explain="从左边第一个非零数字起，到末位数字止的所有数字。", deriv="由测量精度决定。", app="表示近似值的精度。", note="0在中间和末尾都算有效数字，如0.0120有3位有效数字。", hist="误差分析基础。", ext="相对误差与有效数字位数的关系。"),
      T("实数的稠密性", explain="任意两个不相等的实数之间，存在无穷多个有理数和无理数。", deriv="利用区间套或直接构造中间值。", app="极限存在性的基础。", note="稠密但不完备（有理数不完备，实数完备）。", hist="分析严格化的关键概念。", ext="完备性是实数区别于有理数的本质。"),
      T("确界原理", formula=r"\forall S\subseteq\mathbb{R}, S\neq\varnothing, S\text{有上界}\Rightarrow\exists\sup S", explain="非空有上界的实数集必有上确界（最小上界）。", deriv="实数完备性的等价表述，由戴德金分割证明。", app="证明极限存在、最值定理。", note="确界可能属于集合也可能不属于。", hist="实数完备性的核心定理。", ext="确界原理与单调有界、区间套、有限覆盖、柯西准则等价。"),
      T("运算顺序", explain="先乘方开方，再乘除，最后加减；有括号先算括号内。", deriv="约定运算优先级避免歧义。", app="所有数值计算的基础规则。", note="同级运算从左到右。", hist="长期形成的约定。", ext="表达式求值的语法分析。"),
      T("复数概念", formula=r"z=a+bi\ (a,b\in\mathbb{R},\ i^2=-1)", explain="实数的扩充，由实部a和虚部b组成。", deriv="为使x²=-1有解而引入虚数单位i。", app="解方程、电学、信号处理。", note="a=实部，b=虚部；b=0时为实数。", hist="卡尔达诺、欧拉系统使用。", ext="复数域是代数闭域。"),
    ]},
    {"name":"1.2 乘方与开方","color":"#7c3aed","desc":"幂运算、根式","topics":[
      T("乘方", formula=r"a^n=\underbrace{a\cdot a\cdots a}_{n\text{个}}", explain="n个相同因数a相乘的积，记作aⁿ，a叫底数，n叫指数。", deriv="由乘法的重复运算定义。", app="面积体积、增长率、科学记数法。", note="a⁰=1(a≠0)；a⁻ⁿ=1/aⁿ。", hist="古代已有幂的概念，符号由笛卡尔确立。", ext="推广到实数指数幂和复指数。"),
      T("同底数幂乘法", formula=r"a^m\cdot a^n=a^{m+n}", explain="同底数幂相乘，底数不变，指数相加。", deriv="aᵐ·aⁿ = (m个a相乘)·(n个a相乘) = (m+n)个a相乘 = aᵐ⁺ⁿ。", app="化简幂的运算。", note="a≠0时对整数m,n成立。", hist="指数运算基本律。", ext="群的指数律。"),
      T("同底数幂除法", formula=r"a^m\div a^n=a^{m-n}", explain="同底数幂相除，底数不变，指数相减。", deriv="aᵐ/aⁿ = aᵐ·a⁻ⁿ = aᵐ⁻ⁿ。", app="化简幂的运算。", note="a≠0，结果指数可为负。", hist="指数运算基本律。", ext="定义了负整数指数幂。"),
      T("幂的乘方", formula="(a^m)^n=a^{mn}", explain="幂的乘方，底数不变，指数相乘。", deriv="(aᵐ)ⁿ = n个aᵐ相乘 = aᵐ⁺ᵐ⁺…⁺ᵐ(n个) = aᵐⁿ。", app="化简幂的运算。", note="与积的乘方区分。", hist="指数运算基本律。", ext="矩阵幂的类似性质。"),
      T("积的乘方", formula="(ab)^n=a^n b^n", explain="积的乘方等于各因数分别乘方的积。", deriv="(ab)ⁿ = ab·ab·…·ab(n个) = (a·a·…·a)(b·b·…·b) = aⁿbⁿ。", app="化简幂的运算。", note="(a+b)ⁿ≠aⁿ+bⁿ（n>1时）。", hist="指数运算基本律。", ext="交换环中成立。"),
      T("商的乘方", formula=r"\left(\frac{a}{b}\right)^n=\frac{a^n}{b^n}", explain="商的乘方等于分子分母分别乘方的商。", deriv="(a/b)ⁿ = (a·b⁻¹)ⁿ = aⁿ·b⁻ⁿ = aⁿ/bⁿ。", app="化简分式的幂。", note="b≠0。", hist="指数运算基本律。", ext="域中成立。"),
      T("零指数幂", formula=r"a^0=1\ (a\neq 0)", explain="任何非零数的零次幂等于1。", deriv="由aᵐ÷aᵐ=aᵐ⁻ᵐ=a⁰=1(a≠0)导出。", app="统一指数运算律。", note="0⁰无定义（不定式）。", hist="为使指数律在m=n时也成立。", ext="组合数学中0⁰约定为1。"),
      T("负整数指数幂", formula=r"a^{-n}=\frac{1}{a^n}\ (a\neq 0)", explain="非零数的负整数次幂等于其正整数次幂的倒数。", deriv="由a⁰÷aⁿ=a⁻ⁿ=1/aⁿ导出。", app="表示小数、科学记数法。", note="a≠0。", hist="指数律推广到负指数。", ext="群中逆元的幂表示。"),
      T("平方根", formula=r"x^2=a\Rightarrow x=\pm\sqrt{a}", explain="若x²=a，则x叫a的平方根，记作±√a。", deriv="乘方的逆运算。", app="解方程、距离计算。", note="a≥0时才有实平方根；√a表示算术平方根（非负）。", hist="古代已知开平方。", ext="复数中负数也有平方根。"),
      T("算术平方根", formula=r"\sqrt{a}\geq 0\ (a\geq 0)", explain="非负数a的非负平方根叫算术平方根。", deriv="在平方根中取非负的那个。", app="距离公式、二次根式。", note="√a有双重非负性：a≥0且√a≥0。", hist="区分正负根的需要。", ext="一般n次算术根。"),
      T("立方根", formula=r"x^3=a\Rightarrow x=\sqrt[3]{a}", explain="若x³=a，则x叫a的立方根，记作∛a。", deriv="乘方的逆运算。", app="体积计算、解方程。", note="实数都有唯一实立方根，符号与被开方数相同。", hist="古代已知开立方。", ext="奇数次方根的唯一性。"),
      T("n次方根", formula=r"x^n=a\Rightarrow x=\sqrt[n]{a}", explain="若xⁿ=a，则x叫a的n次方根。", deriv="乘方的逆运算。", app="解高次方程。", note="n奇：唯一实根；n偶：a≥0时有两个实根±ⁿ√a，a<0时无实根。", hist="根式理论。", ext="复数域中恒有n个n次方根。"),
      T("根式的性质", formula=r"\sqrt[n]{a^n}=\begin{cases}|a|, & n\text{偶} \\ a, & n\text{奇}\end{cases}", explain="n次根号下a的n次方，偶次取绝对值，奇次取本身。", deriv="由n次方根的定义直接导出。", app="根式化简。", note="注意偶次根式结果非负。", hist="根式运算基本性质。", ext="ⁿ√(ab)=ⁿ√a·ⁿ√b（a,b≥0,n偶时）。"),
      T("分数指数幂", formula=r"a^{m/n}=\sqrt[n]{a^m}", explain="分数指数幂m/n表示开n次方再乘m次方（或反之）。", deriv="要求(a^{1/n})ⁿ=a，故a^{1/n}=ⁿ√a。", app="统一根式与幂的运算。", note="a>0时对一切有理数指数成立。", hist="欧拉系统引入分数指数。", ext="推广到实数指数幂（用极限）。"),
      T("无理数指数幂", formula=r"a^\alpha=\lim_{q\to\alpha}a^q\ (a>0)", explain="无理数指数幂通过有理数指数幂的极限定义。", deriv="用确界或极限定义，保证指数函数连续。", app="指数函数、对数函数的定义域扩张。", note="要求底数a>0。", hist="实数完备性使定义成为可能。", ext="复指数幂与欧拉公式。"),
      T("平方差公式", formula="a^2-b^2=(a+b)(a-b)", explain="两数平方差等于两数和与差的积。", deriv="(a+b)(a-b)=a²-ab+ab-b²=a²-b²。", app="因式分解、简便计算。", note="最基本的乘法公式之一。", hist="古希腊几何代数中已有。", ext="平方和无类似实分解。"),
      T("完全平方公式", formula=r"(a\pm b)^2=a^2\pm 2ab+b^2", explain="两数和（差）的平方等于平方和加（减）两倍积。", deriv="(a+b)²=(a+b)(a+b)=a²+ab+ab+b²=a²+2ab+b²。", app="因式分解、配方法、二次函数。", note="中间项符号与左边一致。", hist="古代几何证明（面积法）。", ext="二项式定理的特例。"),
      T("完全立方公式", formula=r"(a\pm b)^3=a^3\pm 3a^2b+3ab^2\pm b^3", explain="两数和（差）的立方展开式。", deriv="(a+b)³=(a+b)(a+b)²=(a+b)(a²+2ab+b²)=a³+3a²b+3ab²+b³。", app="因式分解、展开。", note="符号正负交替。", hist="二项式定理的特例。", ext="二项式定理：(a+b)ⁿ=∑C(n,k)aⁿ⁻ᵏbᵏ。"),
      T("立方和差公式", formula=r"a^3\pm b^3=(a\pm b)(a^2\mp ab+b^2)", explain="两数立方和（差）分解公式。", deriv="验证：(a+b)(a²-ab+b²)=a³+b³，直接展开。", app="因式分解。", note="注意中间项符号与左边相反。", hist="代数基本恒等式。", ext="n次幂和差的分解。"),
    ]},
    {"name":"1.3 指数与对数","color":"#0f766e","desc":"指数函数、对数运算","topics":[
      T("指数函数", formula=r"y=a^x\ (a>0, a\neq 1)", explain="以常数a为底数、自变量x为指数的函数。", deriv="由实数指数幂定义，要求a>0保证对所有实数x有意义。", app="指数增长/衰减模型、复利计算。", note="a>1时递增，0<a<1时递减；恒过(0,1)。", hist="欧拉深入研究指数函数。", ext="eˣ是最重要的指数函数，其导数等于自身。"),
      T("指数函数性质", explain="指数函数y=aˣ的定义域R，值域(0,+∞)，恒过(0,1)。", deriv="由aˣ>0和a⁰=1导出。", app="解指数方程、指数不等式。", note="a>1时x→-∞,y→0⁺；0<a<1时x→+∞,y→0⁺。", hist="函数性质研究。", ext="指数函数是微分方程y'=y的解。"),
      T("对数的定义", formula=r"a^b=N\Leftrightarrow\log_a N=b", explain="若aᵇ=N(a>0,a≠1)，则b叫以a为底N的对数，记作logₐN。", deriv="指数运算的逆运算。", app="化乘除为加减、简化计算。", note="N>0（真数必须为正）；logₐ1=0，logₐa=1。", hist="纳皮尔1614年发明对数，极大简化天文计算。", ext="对数将乘法群同构到加法群。"),
      T("常用对数与自然对数", formula=r"\lg N=\log_{10}N,\ \ln N=\log_e N", explain="以10为底的对数叫常用对数(lg)，以e为底的叫自然对数(ln)。", deriv="选择便于计算的底数。", app="常用对数用于数量级；自然对数用于微积分。", note="e≈2.71828，是最重要的数学常数之一。", hist="布里格斯推广常用对数；自然对数因导数简单而得名。", ext="换底公式可在任意底数间转换。"),
      T("对数运算法则", formula=r"\log_a(MN)=\log_a M+\log_a N", explain="积的对数等于对数的和。", deriv="设logₐM=p, logₐN=q，则M=aᵖ,N=aᵠ，MN=aᵖ⁺ᵠ，故logₐ(MN)=p+q。", app="化乘为加，简化计算。", note="M,N>0；logₐ(M+N)≠logₐM+logₐN。", hist="对数的核心价值所在。", ext="对数是乘法群到加法群的同构。"),
      T("商的对数", formula=r"\log_a\frac{M}{N}=\log_a M-\log_a N", explain="商的对数等于对数的差。", deriv="类似积的对数，利用aᵖ/aᵠ=aᵖ⁻ᵠ。", app="化除为减。", note="M,N>0。", hist="对数基本性质。", ext="对数的群同构性质。"),
      T("幂的对数", formula=r"\log_a M^n=n\log_a M", explain="幂的对数等于指数乘以底数的对数。", deriv="设logₐM=p，则M=aᵖ，Mⁿ=aⁿᵖ，故logₐMⁿ=np=nlogₐM。", app="将幂运算降为乘法。", note="对一切实数n成立（M>0）。", hist="对数基本性质。", ext="导数(lnx)'=1/x的代数根源。"),
      T("换底公式", formula=r"\log_a b=\frac{\log_c b}{\log_c a}", explain="对数可在任意两个底数间转换。", deriv="设logₐb=x，则aˣ=b，两边取以c为底的对数：xlogₐc... 即x=log_c b/log_c a。", app="计算不同底数的对数。", note="常用推论：logₐb·log_b a=1。", hist="对数计算的核心公式。", ext="推广到多个底数的链式转换。"),
      T("对数函数", formula=r"y=\log_a x\ (a>0, a\neq 1)", explain="指数函数y=aˣ的反函数。", deriv="由反函数定义，定义域(0,+∞)，值域R。", app="数据压缩（分贝、里氏震级）、求解指数方程。", note="a>1时递增，0<a<1时递减；恒过(1,0)。", hist="对数函数与指数函数互为反函数。", ext="lnx的导数为1/x，是微积分的基础。"),
      T("对数函数性质", explain="对数函数y=logₐx定义域(0,+∞)，值域R，恒过(1,0)。", deriv="由指数函数性质反推。", app="解对数方程、对数不等式。", note="a>1时x→0⁺,y→-∞；0<a<1时x→0⁺,y→+∞。", hist="函数研究。", ext="对数函数增长极慢。"),
      T("指数方程", formula=r"a^{f(x)}=a^{g(x)}\Leftrightarrow f(x)=g(x)", explain="底数相同的指数方程可化为指数相等。", deriv="指数函数单调，故aᵘ=aᵛ⟺u=v。", app="解含指数的方程。", note="底数不同时取对数化为代数方程。", hist="超越方程的基本类型。", ext="数值方法求解一般指数方程。"),
      T("对数方程", formula=r"\log_a f(x)=\log_a g(x)\Leftrightarrow f(x)=g(x)>0", explain="底数相同的对数方程可化为真数相等且为正。", deriv="对数函数单调且定义域为正。", app="解含对数的方程。", note="必须验根，确保真数>0。", hist="超越方程的基本类型。", ext="对数方程的增根问题。"),
      T("指数不等式", formula="a^{f(x)}>a^{g(x)}", explain="解指数不等式时需讨论底数a与1的大小关系。", deriv="a>1时指数函数递增，不等号方向不变；0<a<1时递减，不等号反向。", app="解指数不等式。", note="注意底数分类讨论。", hist="单调性的应用。", ext="一般超越不等式的解法。"),
      T("对数不等式", formula=r"\log_a f(x)>\log_a g(x)", explain="解对数不等式时需讨论底数并保证真数为正。", deriv="对数函数单调性+定义域限制。", app="解对数不等式。", note="必须同时满足真数>0和单调性条件。", hist="单调性的应用。", ext="定义域优先原则。"),
      T("指数对数互化", formula=r"a^b=N\Leftrightarrow b=\log_a N", explain="指数式与对数式可互相转化。", deriv="对数的定义。", app="沟通指数与对数运算。", note="转化时注意a>0,a≠1,N>0。", hist="对数的本质。", ext="对数是指数的逆运算。"),
      T("对数恒等式", formula=r"a^{\log_a N}=N,\ \log_a a^N=N", explain="对数与指数互逆的恒等式。", deriv="直接由对数定义。", app="化简指数对数混合表达式。", note="a>0,a≠1,N>0。", hist="对数基本恒等式。", ext="反函数复合的一般性质。"),
      T("自然指数e", formula=r"e=\lim_{n\to\infty}\left(1+\frac{1}{n}\right)^n\approx 2.71828", explain="自然对数的底数，一个超越数。", deriv="由复利极限或级数∑1/n!定义。", app="微积分、指数增长模型。", note="e是无理数也是超越数。", hist="欧拉深入研究，命名为e。", ext="e^(iπ)+1=0（欧拉恒等式）。"),
      T("复利与连续复利", formula=r"A=P\left(1+\frac{r}{n}\right)^{nt}\xrightarrow{n\to\infty}Pe^{rt}", explain="离散复利在n→∞时趋于连续复利Peʳᵗ。", deriv="利用lim(1+r/n)ⁿ=eʳ。", app="金融利息计算、人口增长模型。", note="连续复利是指数增长模型。", hist="伯努利研究复利时发现e。", ext="指数增长/衰减微分方程dA/dt=rA的解。"),
      T("指数函数图象变换", formula="y=a^{x-h}+k", explain="指数函数y=aˣ平移h右k上得到y=a^(x-h)+k。", deriv="由函数图象平移规律。", app="绘制指数型函数图象。", note="h>0右移，k>0上移。", hist="函数变换。", ext="与对数函数图象关于y=x对称。"),
      T("对数函数图象变换", formula=r"y=\log_a(x-h)+k", explain="对数函数y=logₐx平移h右k上。", deriv="由函数图象平移规律。", app="绘制对数型函数图象。", note="定义域受平移影响：x>h。", hist="函数变换。", ext="渐近线也随之平移。"),
      T("指数方程换元法", explain="对形如a^(2x)+b·aˣ+c=0的方程，令t=aˣ化为二次方程。", deriv="令t=aˣ>0，原方程变为t²+bt+c=0。", app="解复合指数方程。", note="注意t>0的限制，负根要舍去。", hist="换元法应用。", ext="也适用于对数方程。"),
      T("对数方程换元法", explain="对形如(logₐx)²+b·logₐx+c=0的方程，令t=logₐx化为二次方程。", deriv="令t=logₐx，原方程变为t²+bt+c=0。", app="解复合对数方程。", note="解得t后再求x，注意真数>0。", hist="换元法应用。", ext="与指数方程换元对偶。"),
      T("指对数混合方程", explain="同时含指数和对数的方程，常需两边取对数或指数。", deriv="利用指对互化。", app="解超越方程。", note="注意定义域和验根。", hist="超越方程。", ext="一般需数值方法求解。"),
    ]},
    {"name":"1.4 三角函数","color":"#c2410c","desc":"六大三角函数、恒等式","topics":[
      T("角的概念与弧度制", formula=r"\theta(\text{rad})=\frac{\pi}{180^\circ}\theta(^\circ)", explain="角由一条射线绕端点旋转形成，弧度制用弧长与半径之比度量角。", deriv="弧长l=rθ，故θ=l/r；整圆2πr对应2π弧度=360°。", app="高等数学中统一使用弧度制。", note="180°=π rad；1°=π/180 rad。", hist="弧度制由欧拉正式引入。", ext="弧度无量纲，使三角函数导数公式简洁。"),
      T("任意角", explain="按逆时针旋转为正角，顺时针为负角，未旋转为零角。", deriv="推广角的概念到任意实数。", app="表示旋转方向和周期运动。", note="终边相同的角相差360°的整数倍。", hist="从0°~360°推广到全体实数。", ext="角的集合与实数集一一对应。"),
      T("象限角", explain="终边落在第几象限就叫第几象限角，终边在坐标轴上叫轴线角。", deriv="由终边位置定义。", app="判断三角函数符号。", note="终边相同角：α+k·360°(k∈Z)。", hist="坐标系中角的分类。", ext="各象限角的三角函数符号规律。"),
      T("正弦函数", formula=r"\sin\alpha=\frac{y}{r}", explain="在角α终边上任取一点P(x,y)，r=√(x²+y²)，则sinα=y/r。", deriv="锐角情形对边/斜边，推广到任意角。", app="周期性、波动、交流电。", note="值域[-1,1]，周期2π。", hist="古代天文学中已有正弦表。", ext="sinx=(e^(ix)-e^(-ix))/(2i)（欧拉公式）。"),
      T("余弦函数", formula=r"\cos\alpha=\frac{x}{r}", explain="角α的余弦为邻边比斜边（推广：x/r）。", deriv="由坐标定义。", app="周期运动、投影。", note="值域[-1,1]，周期2π，偶函数。", hist="余角的正弦。", ext="cosx=(e^(ix)+e^(-ix))/2。"),
      T("正切函数", formula=r"\tan\alpha=\frac{y}{x}=\frac{\sin\alpha}{\cos\alpha}", explain="角α的正切为对边比邻边（推广：y/x）。", deriv="由正弦余弦之比定义。", app="斜率、仰角俯角。", note="定义域x≠π/2+kπ，周期π，奇函数。", hist="与坡度直接相关。", ext="正切函数在每个周期内单调递增。"),
      T("余切函数", formula=r"\cot\alpha=\frac{x}{y}=\frac{\cos\alpha}{\sin\alpha}", explain="角α的余切为邻边比对边。", deriv="正切的倒数。", app="三角恒等变换。", note="定义域x≠kπ，周期π，奇函数。", hist="余角的正切。", ext="cotα=1/tanα。"),
      T("正割余割", formula=r"\sec\alpha=\frac{1}{\cos\alpha},\ \csc\alpha=\frac{1}{\sin\alpha}", explain="正割是余弦的倒数，余割是正弦的倒数。", deriv="由倒数关系定义。", app="三角恒等式、微积分。", note="secα值域|secα|≥1；cscα同。", hist="航海和天文学中使用。", ext="在微积分中导数公式简洁。"),
      T("同角三角函数关系", formula=r"\sin^2\alpha+\cos^2\alpha=1", explain="同一个角的正弦余弦平方和为1。", deriv="由定义sinα=y/r, cosα=x/r，sin²+cos²=(y²+x²)/r²=r²/r²=1。", app="三角函数化简求值。", note="还有tanα=sinα/cosα，1+tan²α=sec²α等。", hist="三角恒等式的基础。", ext="单位圆上的点满足x²+y²=1。"),
      T("商数关系", formula=r"\tan\alpha=\frac{\sin\alpha}{\cos\alpha}", explain="正切等于正弦除以余弦。", deriv="tanα=(y/r)/(x/r)=y/x=sinα/cosα。", app="切化弦、弦化切。", note="cosα≠0时成立。", hist="基本恒等式。", ext="类似cotα=cosα/sinα。"),
      T("倒数关系", formula=r"\sin\alpha\csc\alpha=1,\ \cos\alpha\sec\alpha=1,\ \tan\alpha\cot\alpha=1", explain="正弦与余割、余弦与正割、正切与余切互为倒数。", deriv="由定义直接得出。", app="三角恒等变换。", note="注意定义域限制。", hist="基本恒等式。", ext="六个三角函数三对互逆。"),
      T("诱导公式", formula=r"\sin(\alpha+2k\pi)=\sin\alpha", explain="利用周期性和对称性将任意角三角函数化为锐角三角函数。", deriv="由终边相同角和单位圆对称性。", app="求任意角三角函数值。", note="口诀：奇变偶不变，符号看象限。", hist="简化三角计算的基本工具。", ext="共36组诱导公式可统一记忆。"),
      T("正弦的诱导", formula=r"\sin(\pi-\alpha)=\sin\alpha,\ \sin(\pi+\alpha)=-\sin\alpha", explain="正弦关于y轴对称，关于原点中心对称。", deriv="由单位圆上点的坐标对称性。", app="化简三角函数。", note="sin(-α)=-sinα（奇函数）。", hist="单位圆对称性。", ext="sin(π/2-α)=cosα。"),
      T("余弦的诱导", formula=r"\cos(\pi-\alpha)=-\cos\alpha,\ \cos(\pi+\alpha)=-\cos\alpha", explain="余弦关于原点中心对称。", deriv="单位圆对称性。", app="化简三角函数。", note="cos(-α)=cosα（偶函数）。", hist="单位圆对称性。", ext="cos(π/2-α)=sinα。"),
      T("和角公式", formula=r"\sin(\alpha+\beta)=\sin\alpha\cos\beta+\cos\alpha\sin\beta", explain="两角和的正弦展开式。", deriv="用单位圆上两点距离或向量点积推导。", app="三角恒等变换、求角。", note="是所有三角恒等式的基础。", hist="托勒密已有类似结果。", ext="由和角公式可推出差角、倍角、半角公式。"),
      T("余弦和角公式", formula=r"\cos(\alpha+\beta)=\cos\alpha\cos\beta-\sin\alpha\sin\beta", explain="两角和的余弦展开式。", deriv="由单位圆或复数乘法推导。", app="三角恒等变换。", note="与正弦和角公式符号规律不同。", hist="核心三角恒等式。", ext="用复数证明：cos(α+β)+isin(α+β)=(cosα+isinα)(cosβ+isinβ)。"),
      T("正切和角公式", formula=r"\tan(\alpha+\beta)=\frac{\tan\alpha+\tan\beta}{1-\tan\alpha\tan\beta}", explain="两角和的正切公式。", deriv="由sin(α+β)/cos(α+β)，分子分母同除以cosαcosβ。", app="求两角和的正切。", note="分母不为零，且各正切有意义。", hist="由和角公式导出。", ext="tan(α-β)=(tanα-tanβ)/(1+tanαtanβ)。"),
      T("倍角公式", formula=r"\sin 2\alpha=2\sin\alpha\cos\alpha", explain="二倍角的正弦公式。", deriv="令β=α代入和角公式。", app="降次、化简。", note="cos2α=cos²α-sin²α=2cos²α-1=1-2sin²α。", hist="和角公式的直接推论。", ext="倍角公式的推广（多倍角）。"),
      T("余弦倍角", formula=r"\cos 2\alpha=\cos^2\alpha-\sin^2\alpha=2\cos^2\alpha-1=1-2\sin^2\alpha", explain="二倍角余弦的三种形式。", deriv="由cos(α+α)展开，再用sin²+cos²=1变形。", app="降幂公式的来源。", note="三种形式各有用途。", hist="倍角公式。", ext="由此得降幂公式cos²α=(1+cos2α)/2。"),
      T("半角公式", formula=r"\sin\frac{\alpha}{2}=\pm\sqrt{\frac{1-\cos\alpha}{2}}", explain="半角的正弦公式，符号由α/2所在象限决定。", deriv="由cos2α=1-2sin²α反解。", app="求半角三角函数值。", note="符号由α/2象限确定。", hist="倍角公式的逆用。", ext="tan(α/2)=sinα/(1+cosα)=(1-cosα)/sinα。"),
      T("和差化积", formula=r"\sin\alpha+\sin\beta=2\sin\frac{\alpha+\beta}{2}\cos\frac{\alpha-\beta}{2}", explain="两个正弦的和化为积的形式。", deriv="令α=(u+v)/2, β=(u-v)/2代入和角公式。", app="三角恒等变换、求积。", note="共四组和差化积公式。", hist="三角恒等式。", ext="与积化和差互逆。"),
      T("积化和差", formula=r"\sin\alpha\cos\beta=\frac{1}{2}[\sin(\alpha+\beta)+\sin(\alpha-\beta)]", explain="正弦余弦的积化为和差。", deriv="由和角与差角公式相加/减。", app="积分计算、信号处理。", note="共四组积化和差公式。", hist="三角恒等式。", ext="傅里叶分析的基础工具。"),
      T("辅助角公式", formula=r"a\sin x+b\cos x=\sqrt{a^2+b^2}\sin(x+\varphi)", explain="将同角正余弦线性组合化为单一正弦函数。", deriv="展开右端对比系数，得cosφ=a/√(a²+b²), sinφ=b/√(a²+b²)。", app="求最值、化简。", note="φ满足tanφ=b/a。", hist="三角恒等式的重要应用。", ext="是简谐运动合成的数学基础。"),
      T("正弦定理", formula=r"\frac{a}{\sin A}=\frac{b}{\sin B}=\frac{c}{\sin C}=2R", explain="三角形中各边与对角正弦之比相等，等于外接圆直径。", deriv="由外接圆上同弧所对圆周角相等，或向量法证明。", app="解三角形（已知两角一边或两边一对角）。", note="R为外接圆半径。", hist="古希腊已有球面正弦定理。", ext="推广到球面三角形。"),
      T("余弦定理", formula=r"a^2=b^2+c^2-2bc\cos A", explain="三角形一边的平方等于另两边平方和减去两倍积乘夹角余弦。", deriv="由向量的模长平方或坐标法推导。", app="解三角形（已知两边夹角或三边）。", note="勾股定理是其特例（A=90°时cosA=0）。", hist="欧几里得《几何原本》已有几何表述。", ext="推广到高维向量夹角。"),
      T("三角形面积公式", formula=r"S=\frac{1}{2}ab\sin C", explain="三角形面积等于两边及其夹角正弦乘积的一半。", deriv="由底乘高/2，高为bsinC。", app="求三角形面积。", note="还有海伦公式S=√[p(p-a)(p-b)(p-c)]。", hist="古代测量学基础。", ext="用向量叉积表示面积。"),
      T("正弦函数图象", formula=r"y=\sin x", explain="正弦函数图象是周期为2π的波浪线。", deriv="由单位圆上点的纵坐标描点得到。", app="波动、交流电。", note="五点法作图：(0,0),(π/2,1),(π,0),(3π/2,-1),(2π,0)。", hist="三角学与函数结合。", ext="正弦曲线是最简单的周期函数。"),
      T("余弦函数图象", formula=r"y=\cos x", explain="余弦函数图象是正弦曲线向左平移π/2。", deriv="cosx=sin(x+π/2)。", app="相位差、振动。", note="偶函数，关于y轴对称。", hist="由正弦平移得到。", ext="相位变换的基础。"),
      T("正切函数图象", formula=r"y=\tan x", explain="正切函数图象是周期为π的曲线，有垂直渐近线。", deriv="由定义和周期性。", app="斜率、周期性。", note="渐近线x=π/2+kπ；在每个周期内递增。", hist="三角函数图象。", ext="无最值，值域R。"),
      T("积化和差公式", formula=r"\sin\alpha\cos\beta=\frac{1}{2}[\sin(\alpha+\beta)+\sin(\alpha-\beta)]", explain="将三角函数乘积转化为和差。", deriv="由和角公式加减消元。", app="积分、化简。", note="共四个公式。", hist="三角恒等变换。", ext="与和差化积互逆。"),
      T("和差化积公式", formula=r"\sin\alpha+\sin\beta=2\sin\frac{\alpha+\beta}{2}\cos\frac{\alpha-\beta}{2}", explain="将三角函数和差转化为乘积。", deriv="由积化和差反推。", app="化简、证明。", note="共四个公式。", hist="三角恒等变换。", ext="与积化和差互逆。"),
      T("三倍角公式", formula=r"\sin 3\alpha=3\sin\alpha-4\sin^3\alpha", explain="三倍角的正弦、余弦公式。", deriv="由和角公式sin(2α+α)展开。", app="三角化简。", note="cos3α=4cos³α-3cosα。", hist="三角恒等变换。", ext="与三次方程求解相关。"),
      T("万能公式", formula=r"\sin\alpha=\frac{2\tan(\alpha/2)}{1+\tan^2(\alpha/2)}", explain="用半角正切表示各三角函数。", deriv="由二倍角公式推导。", app="三角有理式积分。", note="令t=tan(α/2)。", hist="三角恒等变换。", ext="将三角化为代数有理式。"),
      T("海伦公式", formula=r"S=\sqrt{p(p-a)(p-b)(p-c)}", explain="用三边长表示三角形面积，p为半周长。", deriv="由余弦定理和面积公式推导。", app="已知三边求面积。", note="p=(a+b+c)/2。", hist="海伦（古希腊）。", ext="与秦九韶三斜求积等价。"),
    ]},
    {"name":"1.5 反三角函数","color":"#7c3aed","desc":"反三角定义与性质","topics":[
      T("反正弦函数", formula=r"y=\arcsin x,\ x\in[-1,1],\ y\in[-\frac{\pi}{2},\frac{\pi}{2}]", explain="正弦函数在[-π/2,π/2]上的反函数。", deriv="限制正弦到单调区间后取反函数。", app="求角度、三角方程。", note="arcsin(sinx)不一定等于x（需x在主值区间）。", hist="反三角函数研究。", ext="定义域[-1,1]，值域[-π/2,π/2]，奇函数。"),
      T("反余弦函数", formula=r"y=\arccos x,\ x\in[-1,1],\ y\in[0,\pi]", explain="余弦函数在[0,π]上的反函数。", deriv="限制余弦到单调递减区间后取反函数。", app="求角度。", note="arccosx+arcsinx=π/2。", hist="反三角函数。", ext="非奇非偶，递减。"),
      T("反正切函数", formula=r"y=\arctan x,\ x\in\mathbb{R},\ y\in(-\frac{\pi}{2},\frac{\pi}{2})", explain="正切函数在(-π/2,π/2)上的反函数。", deriv="限制正切到单调区间后取反函数。", app="求角度、斜率转角度。", note="水平渐近线y=±π/2。", hist="反三角函数。", ext="奇函数，递增，值域开区间。"),
      T("反余切函数", formula=r"y=\operatorname{arccot} x,\ x\in\mathbb{R},\ y\in(0,\pi)", explain="余切函数在(0,π)上的反函数。", deriv="类似反正切。", app="求角度。", note="arctanx+arccotx=π/2。", hist="反三角函数。", ext="递减。"),
      T("反正弦性质", formula=r"\arcsin(-x)=-\arcsin x", explain="反正弦是奇函数。", deriv="由正弦是奇函数推出。", app="化简反三角表达式。", note="sin(arcsinx)=x(x∈[-1,1])。", hist="反三角恒等式。", ext="arcsinx+arccosx=π/2。"),
      T("反三角恒等式", formula=r"\arcsin x+\arccos x=\frac{\pi}{2}", explain="反正弦与反余弦之和恒为π/2。", deriv="设α=arcsinx，则sinα=x，cos(π/2-α)=x，且π/2-α∈[0,π]=arccos的值域，故arccosx=π/2-α。", app="化简反三角表达式。", note="对一切x∈[-1,1]成立。", hist="反三角恒等式。", ext="类似arctanx+arccotx=π/2。"),
      T("反三角函数求值", explain="求反三角函数值时，先确定是否在定义域内，再找对应主值角。", deriv="由反函数定义。", app="三角方程求解。", note="注意主值区间限制。", hist="反三角基本运算。", ext="arcsin(sinx)=x仅当x∈[-π/2,π/2]。"),
      T("反三角复合", formula=r"\sin(\arccos x)=\sqrt{1-x^2}", explain="反三角函数的三角函数化简。", deriv="设α=arccosx，则cosα=x，sinα=√(1-x²)（因α∈[0,π],sinα≥0）。", app="化简表达式。", note="注意符号由反三角的值域决定。", hist="反三角恒等变换。", ext="tan(arcsinx)=x/√(1-x²)。"),
      T("反正切恒等式", formula=r"\arctan x+\arctan\frac{1}{x}=\frac{\pi}{2}\ (x>0)", explain="正数x的反正切与反余切之和为π/2。", deriv="设α=arctanx，则tanα=x，cotα=1/x，故arctan(1/x)=π/2-α。", app="化简反三角表达式。", note="x<0时结果为-π/2。", hist="反三角恒等式。", ext="推广到arctan a+arctan b=arctan[(a+b)/(1-ab)]。"),
      T("反三角函数导数预备", formula=r"(\arcsin x)'=\frac{1}{\sqrt{1-x^2}}", explain="反正弦的导数（微积分预备知识）。", deriv="由反函数求导法则推导。", app="微积分基础。", note="(arccosx)'=-1/√(1-x²)；(arctanx)'=1/(1+x²)。", hist="微积分发展。", ext="反三角函数的不定积分。"),
      T("反三角方程", explain="含反三角函数的方程。", deriv="通过设辅助角转化为代数方程。", app="解三角方程。", note="注意反三角的值域限制。", hist="三角方程。", ext="arcsin x=α则x=sinα且α∈[-π/2,π/2]。"),
      T("余弦定理反三角应用", explain="用反余弦求三角形内角。", deriv="由余弦定理cosC=(a²+b²-c²)/(2ab)，再用arccos求角。", app="解三角形。", note="结果在[0,π]内，与arccos值域一致。", hist="三角学应用。", ext="与正弦定理配合使用。"),
    ]},
    {"name":"1.6 代数式与分式","color":"#2563eb","desc":"整式、分式、根式化简","topics":[
      T("代数式", explain="用运算符号把数和字母连接而成的式子。", deriv="由具体数值计算抽象而来。", app="表示数量关系、列方程。", note="单独一个数或字母也是代数式。", hist="代数符号化的产物。", ext="代数式分为有理式和无理式。"),
      T("整式", explain="单项式和多项式的统称，分母不含字母。", deriv="由数与字母的积或和组成。", app="代数运算的基本对象。", note="整式包括单项式（一项）和多项式（多项）。", hist="代数学核心概念。", ext="多项式环。"),
      T("单项式", formula="ax^n", explain="数与字母的积，单独一个数或字母也是单项式。", deriv="由乘法运算构成。", app="表示简单数量关系。", note="系数、次数是单项式的两个要素。", hist="代数基本概念。", ext="单项式构成多项式的基。"),
      T("多项式", formula=r"a_nx^n+\cdots+a_1x+a_0", explain="几个单项式的和，按降幂排列。", deriv="由单项式相加构成。", app="方程、函数、插值。", note="次数是最高次项的次数。", hist="代数学核心研究对象。", ext="多项式环的唯一分解定理。"),
      T("同类项", explain="所含字母相同且相同字母指数也相同的单项式。", deriv="由项的结构定义。", app="合并同类项化简多项式。", note="合并时系数相加减，字母和指数不变。", hist="代数化简基础。", ext="同类项合并是多项式加法的本质。"),
      T("合并同类项", explain="把多项式中的同类项合并成一项。", deriv="利用分配律ac+bc=(a+b)c。", app="化简多项式。", note="只合并系数，字母部分不变。", hist="代数化简基本操作。", ext="多项式标准化。"),
      T("整式加减", explain="整式加减即去括号后合并同类项。", deriv="由加法运算律和合并同类项。", app="化简表达式、求值。", note="去括号时注意符号变化。", hist="代数运算。", ext="多项式环的加法。"),
      T("整式乘法", explain="单项式乘单项式、单项式乘多项式、多项式乘多项式。", deriv="利用乘法分配律和同底数幂乘法。", app="展开、因式分解逆运算。", note="多项式乘多项式用分配律逐项相乘。", hist="代数运算。", ext="多项式环的乘法。"),
      T("分式", formula=r"\frac{A}{B}\ (B\text{含字母}, B\neq 0)", explain="分子分母都是整式，分母含字母的式子。", deriv="由除法运算引入。", app="表示比率、分式方程。", note="分母不为零；分式基本性质：A/B=AC/BC(C≠0)。", hist="分数概念的推广。", ext="有理函数域。"),
      T("分式基本性质", formula=r"\frac{A}{B}=\frac{A\cdot C}{B\cdot C}=\frac{A\div C}{B\div C}\ (C\neq 0)", explain="分式分子分母同乘（除以）非零整式，值不变。", deriv="由分数基本性质推广。", app="约分、通分。", note="C必须非零且使原分式有意义。", hist="分式运算基础。", ext="分式域的构造。"),
      T("约分", explain="把分式分子分母的公因式约去。", deriv="利用分式基本性质。", app="化简分式。", note="约去的是公因式，要彻底约分到最简。", hist="分式化简。", ext="最简分式（分子分母互质）。"),
      T("通分", explain="把异分母分式化为同分母分式。", deriv="利用分式基本性质，分子分母同乘适当整式。", app="分式加减运算。", note="最简公分母是各分母系数最小公倍数与字母最高次幂的积。", hist="分式运算。", ext="推广到多个分式。"),
      T("分式加减", formula=r"\frac{A}{B}\pm\frac{C}{D}=\frac{AD\pm BC}{BD}", explain="异分母分式加减先通分再加减。", deriv="利用通分转化为同分母。", app="分式运算。", note="结果要约分到最简。", hist="分式运算。", ext="有理函数的加法。"),
      T("分式乘除", formula=r"\frac{A}{B}\cdot\frac{C}{D}=\frac{AC}{BD},\ \frac{A}{B}\div\frac{C}{D}=\frac{AD}{BC}", explain="分式乘除：分子乘分子、分母乘分母；除法变乘法取倒数。", deriv="由分数乘除法推广。", app="分式运算。", note="除法先化为乘法再约分。", hist="分式运算。", ext="有理函数域的乘法。"),
      T("二次根式", formula=r"\sqrt{a}\ (a\geq 0)", explain="形如√a(a≥0)的式子。", deriv="由平方根概念引入。", app="表示无理数、几何计算。", note="双重非负：a≥0且√a≥0。", hist="根式运算。", ext="n次根式。"),
      T("二次根式性质", formula=r"\sqrt{ab}=\sqrt{a}\cdot\sqrt{b}\ (a,b\geq 0)", explain="积的算术平方根等于各因式算术平方根的积。", deriv="由(√a·√b)²=ab推出。", app="根式化简。", note="a,b必须非负。", hist="根式运算性质。", ext="√(a/b)=√a/√b(a≥0,b>0)。"),
      T("分母有理化", explain="将分母中的根号化去。", deriv="分子分母同乘分母的有理化因式。", app="根式化简、求值。", note="√a的有理化因式是√a；√a±√b的是√a∓√b。", hist="根式化简技巧。", ext="共轭根式的应用。"),
      T("最简二次根式", explain="被开方数不含分母，且不含能开尽方的因数或因式。", deriv="由化简目标定义。", app="根式运算的最终形式。", note="运算结果要化为最简二次根式。", hist="根式标准化。", ext="同类二次根式才能合并。"),
    ]},
    {"name":"1.7 因式分解","color":"#0f766e","desc":"分解方法与技巧","topics":[
      T("因式分解", explain="把一个多项式化为几个整式的积的形式。", deriv="整式乘法的逆运算。", app="解方程、化简、求值。", note="分解要彻底（到不可约因式）。", hist="代数学基本问题。", ext="多项式环的唯一分解性。"),
      T("提公因式法", formula="ma+mb+mc=m(a+b+c)", explain="把多项式各项的公因式提到括号外面。", deriv="逆用分配律。", app="因式分解的首选方法。", note="公因式取系数最大公约数与字母最低次幂。", hist="最基本的分解方法。", ext="分组提公因式。"),
      T("公式法", explain="利用乘法公式反向进行因式分解。", deriv="乘法公式的逆用。", app="分解特殊形式的多项式。", note="常用：平方差、完全平方、立方和差。", hist="代数恒等式的应用。", ext="更多公式如完全立方、十字相乘等。"),
      T("十字相乘法", formula="x^2+(p+q)x+pq=(x+p)(x+q)", explain="对二次三项式x²+(p+q)x+pq分解为(x+p)(x+q)。", deriv="逆用多项式乘法。", app="分解二次三项式。", note="找两个数p,q使p+q=一次项系数，pq=常数项。", hist="分解技巧。", ext="推广到ax²+bx+c（a≠1）。"),
      T("分组分解法", explain="将多项式适当分组后分别分解，再提取公因式。", deriv="利用分组创造公因式。", app="分解四项及以上多项式。", note="分组原则：分组后能提公因式或用公式。", hist="分解技巧。", ext="灵活分组是关键。"),
      T("配方法分解", explain="通过添加项配成完全平方再分解。", deriv="a²+2ab+b²=(a+b)²的逆用。", app="分解二次式、解二次方程。", note="配方法是重要的代数变形技巧。", hist="古代巴比伦已用配方法解方程。", ext="求二次函数顶点、解二次方程。"),
      T("求根公式法", formula="ax^2+bx+c=a(x-x_1)(x-x_2)", explain="若二次方程有根x₁,x₂，则二次式可分解为a(x-x₁)(x-x₂)。", deriv="由因式定理：若f(r)=0则(x-r)是因式。", app="分解二次三项式（尤其判别式非负时）。", note="判别式<0时在实数域不可约。", hist="因式定理的应用。", ext="推广到高次多项式。"),
      T("因式定理", formula=r"f(a)=0\Leftrightarrow(x-a)\text{是}f(x)\text{的因式}", explain="多项式f(x)有因式(x-a)当且仅当f(a)=0。", deriv="由带余除法f(x)=(x-a)q(x)+r，r=f(a)。", app="分解多项式、求根。", note="是高次多项式分解的重要工具。", hist="多项式理论基本定理。", ext="余数定理：f(a)等于f(x)除以(x-a)的余数。"),
      T("换元法分解", explain="引入新变量简化多项式结构后分解。", deriv="变量替换化繁为简。", app="分解复杂多项式。", note="换元后注意还原。", hist="代数化简技巧。", ext="常用换元：整体换元、倒数换元、平均换元。"),
      T("待定系数法分解", explain="设出分解后的形式，再比较系数求出待定系数。", deriv="利用多项式恒等条件。", app="分解结构特殊的多项式。", note="假设的形式必须正确。", hist="代数方法。", ext="与多项式插值的联系。"),
      T("分解彻底性", explain="因式分解要分解到不能再分解为止（在指定数域内）。", deriv="由多项式唯一分解定理保证。", app="确保分解结果最简。", note="同一多项式在不同数域分解结果不同（如x²-2在Q不可约，在R可约）。", hist="数域对分解的影响。", ext="复数域上多项式总可分解为一次因式之积。"),
      T("双十字相乘法", explain="对二次齐次式如Ax²+Bxy+Cy²+Dx+Ey+F用双十字相乘分解。", deriv="十字相乘法的推广，分两次交叉相乘。", app="分解二元二次多项式。", note="适用于含交叉项xy的多项式。", hist="代数技巧。", ext="可推广到三元二次齐次式。"),
      T("余数定理", formula="f(x)=(x-a)q(x)+f(a)", explain="多项式f(x)除以(x-a)的余数等于f(a)。", deriv="由带余除法：f(x)=(x-a)q(x)+r，代入x=a得r=f(a)。", app="不求商直接求余数。", note="因式定理是其余数为0的特例。", hist="多项式理论。", ext="综合除法。"),
    ]},
    {"name":"1.8 方程","color":"#c2410c","desc":"各类方程解法","topics":[
      T("方程与方程的解", explain="含未知数的等式叫方程；使方程成立的未知数值叫方程的解。", deriv="由等式概念推广。", app="建模求解未知量。", note="解方程要注意增根和失根。", hist="最古老的数学问题之一。", ext="方程论与伽罗瓦理论。"),
      T("一元一次方程", formula=r"ax+b=0\Rightarrow x=-\frac{b}{a}", explain="只含一个未知数且次数为1的方程。", deriv="移项、合并同类项、系数化1。", app="最基本的方程，大量实际问题。", note="a≠0时有唯一解。", hist="古代已系统求解。", ext="线性方程的推广。"),
      T("二元一次方程组", formula=r"\begin{cases}a_1x+b_1y=c_1\\a_2x+b_2y=c_2\end{cases}", explain="由两个二元一次方程组成的方程组。", deriv="代入消元或加减消元。", app="两变量实际问题。", note="解的情况：唯一解、无解、无穷多解。", hist="线性方程组基础。", ext="推广到n元线性方程组（矩阵法）。"),
      T("代入消元法", explain="将一个方程中的一个未知数用另一个表示，代入另一方程。", deriv="等量代换。", app="解方程组。", note="选择系数简单的变量代入。", hist="消元法。", ext="高斯消元法的特例。"),
      T("加减消元法", explain="将方程组中某未知数系数化为相同或相反后加减消去。", deriv="等式性质。", app="解方程组。", note="系数化相同用减法，化相反用加法。", hist="消元法。", ext="线性代数的行变换。"),
      T("一元二次方程", formula=r"ax^2+bx+c=0\ (a\neq 0)", explain="只含一个未知数且最高次为2的方程。", deriv="配方法或因式分解法。", app="抛物线、最值、实际问题。", note="判别式Δ=b²-4ac决定根的情况。", hist="公元前2000年巴比伦已会解。", ext="韦达定理、求根公式。"),
      T("配方法解二次方程", formula=r"ax^2+bx+c=0\Rightarrow x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}", explain="通过配方将二次方程化为完全平方求解。", deriv="两边除以a，配方(x+b/2a)²=(b²-4ac)/4a²，开方求解。", app="解二次方程、推导求根公式。", note="当Δ≥0时有实根。", hist="求根公式的推导方法。", ext="配方法是二次问题的通用技巧。"),
      T("求根公式", formula=r"x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}", explain="一元二次方程的求根公式。", deriv="由配方法推导。", app="直接求解二次方程。", note="Δ=b²-4ac，Δ>0两不等实根，Δ=0两等根，Δ<0无实根。", hist="公元9世纪花拉子米给出文字版。", ext="推广到三次、四次方程求根公式。"),
      T("判别式", formula=r"\Delta=b^2-4ac", explain="一元二次方程根的判别式。", deriv="由求根公式中根号内的部分定义。", app="判断根的情况。", note="Δ>0：两个不等实根；Δ=0：两个相等实根；Δ<0：无实根（有两共轭复根）。", hist="方程论基础。", ext="推广到高次方程的判别式。"),
      T("韦达定理", formula=r"x_1+x_2=-\frac{b}{a},\ x_1x_2=\frac{c}{a}", explain="一元二次方程两根之和与积的关系。", deriv="由求根公式x₁,x₂相加相乘化简。", app="不解方程求根的和积、构造方程。", note="对复根也成立。", hist="韦达16世纪发现。", ext="推广到n次方程的根与系数关系。"),
      T("因式分解法解方程", explain="将方程一边因式分解，另一边为零，令各因式为零求解。", deriv="若ab=0则a=0或b=0。", app="解可分解的方程。", note="必须右边为零。", hist="解方程基本方法。", ext="高次方程的因式分解法。"),
      T("分式方程", explain="分母含未知数的方程。", deriv="去分母化为整式方程。", app="实际问题建模。", note="必须验根（去分母可能产生增根）。", hist="方程类型。", ext="有理方程。"),
      T("无理方程", explain="根号内含未知数的方程。", deriv="换元或平方去根号。", app="几何、物理问题。", note="必须验根（平方可能产生增根）。", hist="方程类型。", ext="根式可解条件。"),
      T("绝对值方程", formula="|f(x)|=c", explain="含绝对值的方程。", deriv="分类讨论去绝对值或平方。", app="距离、分段问题。", note="c<0时无解；c=0时f(x)=0；c>0时f(x)=±c。", hist="方程类型。", ext="绝对值不等式。"),
      T("方程组的解", explain="方程组中各方程公共解。", deriv="同时满足所有方程。", app="多变量建模。", note="注意解的存在性和唯一性。", hist="方程组理论。", ext="线性方程组的矩阵解法。"),
      T("增根与失根", explain="解方程变形过程中产生的不满足原方程的根叫增根，丢失的根叫失根。", deriv="非同解变形导致。", app="验根的依据。", note="去分母、平方等操作可能增根；除以含未知数式子可能失根。", hist="方程变形的等价性。", ext="同解原理。"),
      T("一元高次方程", explain="次数≥3的整式方程。", deriv="由多项式定义。", app="高次问题。", note="三次、四次有求根公式，五次及以上无通用求根公式（阿贝尔定理）。", hist="方程论。", ext="伽罗瓦理论给出可解性判据。"),
      T("因式分解法解高次方程", explain="将高次方程因式分解为低次方程求解。", deriv="若f(x)=g(x)h(x)=0则g(x)=0或h(x)=0。", app="解可分解的高次方程。", note="先试有理根（有理根定理）。", hist="解方程。", ext="有理根定理：可能有理根为常数项因数/首项系数因数。"),
      T("二元二次方程组", explain="含两个未知数且最高次为2的方程组。", deriv="消元降次。", app="解析几何交点。", note="常用代入消元转化为一元二次。", hist="方程组。", ext="直线与圆锥曲线交点。"),
      T("无理方程解法", formula=r"\sqrt{f(x)}=g(x)", explain="含根号的方程，通过平方或换元求解。", deriv="两边平方去根号。", app="几何问题。", note="必须验根，平方可能增根。", hist="方程类型。", ext="注意g(x)≥0的隐含条件。"),
      T("指数方程解法", formula="a^{f(x)}=b", explain="含指数的方程。", deriv="取对数或化为同底。", app="增长衰减问题。", note="a>0,a≠1。", hist="超越方程。", ext="a^f(x)=a^g(x)⟺f(x)=g(x)。"),
      T("对数方程解法", formula=r"\log_a f(x)=b", explain="含对数的方程。", deriv="化为指数式或同底比较。", app="对数问题。", note="必须验根，真数>0。", hist="超越方程。", ext="log_a f(x)=log_a g(x)⟺f(x)=g(x)>0。"),
    ]},
    {"name":"1.9 不等式","color":"#7c3aed","desc":"不等式性质与证明","topics":[
      T("不等式", explain="用不等号(>、<、≥、≤、≠)连接的式子。", deriv="由实数的有序性定义。", app="比较大小、求范围、优化。", note="解不等式要注意不等号方向变化。", hist="分析学基础。", ext="不等式是分析的核心工具。"),
      T("不等式性质1", formula=r"a>b\Leftrightarrow b<a", explain="不等式的对称性（反对称）。", deriv="由实数序关系的反对称性。", app="不等式变形。", note="a>b与b<a等价。", hist="序的基本性质。", ext="偏序关系的反对称性。"),
      T("不等式性质2", formula=r"a>b,\ b>c\Rightarrow a>c", explain="不等式的传递性。", deriv="实数序关系的传递性。", app="不等式传递比较。", note="传递性是不等式证明的常用工具。", hist="序的基本性质。", ext="偏序关系的传递性。"),
      T("不等式性质3", formula=r"a>b\Rightarrow a+c>b+c", explain="不等式两边同加一数，不等号方向不变。", deriv="加法保序。", app="移项。", note="移项要变号。", hist="序与加法的相容性。", ext="有序群的性质。"),
      T("不等式性质4", formula=r"a>b,\ c>0\Rightarrow ac>bc", explain="不等式两边同乘正数，不等号方向不变；乘负数则反向。", deriv="乘法与序的相容性。", app="系数化1。", note="乘负数时不等号变向！", hist="序与乘法的相容性。", ext="有序域的性质。"),
      T("不等式性质5", formula=r"a>b>0\Rightarrow a^n>b^n>0", explain="正数不等式两边乘方（n为正整数），不等号方向不变。", deriv="由性质4递推。", app="不等式变形。", note="要求a,b>0。", hist="幂的单调性。", ext="开方也有类似性质。"),
      T("比较法", explain="通过比较两边的大小来证明不等式。", deriv="作差与0比较，或作商与1比较。", app="不等式证明。", note="作差法最常用。", hist="不等式证明基本方法。", ext="比较法是最直接的证明方法。"),
      T("基本不等式", formula=r"a^2+b^2\geq 2ab", explain="对任意实数a,b，a²+b²≥2ab，等号当且仅当a=b。", deriv="由(a-b)²≥0展开得a²-2ab+b²≥0，即a²+b²≥2ab。", app="求最值、证明不等式。", note="等号当且仅当a=b。", hist="最基本的不等式。", ext="推广到均值不等式。"),
      T("均值不等式", formula=r"\frac{a+b}{2}\geq\sqrt{ab}\ (a,b>0)", explain="两个正数的算术平均数不小于几何平均数。", deriv="由(√a-√b)²≥0推出。", app="求最值（积定和最小，和定积最大）。", note="等号当且仅当a=b；要求a,b>0。", hist="均值不等式链：调和≤几何≤算术≤平方。", ext="推广到n个正数。"),
      T("均值不等式链", formula=r"\frac{n}{\sum\frac{1}{a_i}}\leq\sqrt[n]{\prod a_i}\leq\frac{\sum a_i}{n}\leq\sqrt{\frac{\sum a_i^2}{n}}", explain="调和平均≤几何平均≤算术平均≤平方平均。", deriv="数学归纳法或凸函数Jensen不等式。", app="求最值、证明。", note="等号当且仅当所有aᵢ相等。", hist="均值不等式的完整形式。", ext="加权均值不等式。"),
      T("绝对值不等式", formula=r"|a|-|b|\leq|a\pm b|\leq|a|+|b|", explain="绝对值的三角不等式。", deriv="由-|a|≤a≤|a|同理对b，相加导出。", app="估计、证明。", note="|a+b|≤|a|+|b|等号当且仅当ab≥0。", hist="分析学基本不等式。", ext="推广到向量的三角不等式。"),
      T("一元一次不等式", formula="ax>b", explain="只含一个未知数且次数为1的不等式。", deriv="移项、系数化1。", app="求范围。", note="a>0时x>b/a；a<0时x<b/a；a=0时讨论b。", hist="不等式基础。", ext="线性不等式组。"),
      T("一元二次不等式", formula="ax^2+bx+c>0", explain="含一个未知数且最高次为2的不等式。", deriv="结合二次函数图象与根。", app="求范围。", note="看开口方向和判别式确定解集。", hist="二次不等式。", ext="高次不等式用穿根法。"),
      T("分式不等式", formula=r"\frac{f(x)}{g(x)}>0\Leftrightarrow f(x)g(x)>0", explain="分母含未知数的不等式。", deriv="转化为整式不等式（注意分母不为零）。", app="求范围。", note="不能直接去分母（不知符号）。", hist="不等式类型。", ext="高次分式不等式用穿根法。"),
      T("绝对值不等式解法", formula=r"|f(x)|<a\Leftrightarrow -a<f(x)<a", explain="绝对值不等式的等价转化。", deriv="由绝对值定义。", app="解绝对值不等式。", note="|f(x)|>a⟺f(x)>a或f(x)<-a。", hist="不等式解法。", ext="多个绝对值用零点分段法。"),
      T("不等式恒成立", explain="不等式对定义域内所有x都成立。", deriv="转化为最值问题：f(x)≥a恒成立⟺f(x)min≥a。", app="求参数范围。", note="注意分离参数法。", hist="不等式应用。", ext="存在性问题与恒成立问题对偶。"),
      T("分析法证明不等式", explain="从结论出发，逐步寻求使它成立的充分条件。", deriv="执果索因。", app="不等式证明。", note="常与综合法结合使用。", hist="证明方法。", ext="逆向思维。"),
      T("综合法证明不等式", explain="从已知条件出发，利用不等式性质推导出结论。", deriv="由因导果。", app="不等式证明。", note="常用基本不等式作为起点。", hist="证明方法。", ext="与分析法互逆。"),
      T("放缩法证明不等式", explain="将不等式一侧适当放大或缩小以达到证明目的。", deriv="利用不等式传递性。", app="不等式证明、数列求和估计。", note="放缩要适度，不能过头。", hist="不等式技巧。", ext="裂项放缩、均值放缩。"),
      T("柯西不等式", formula=r"(\sum a_i b_i)^2\leq(\sum a_i^2)(\sum b_i^2)", explain="两组实数的柯西不等式。", deriv="由判别式法或向量数量积。", app="证明不等式、求最值。", note="等号当且仅当aᵢ/bᵢ为常数。", hist="柯西1821年提出。", ext="推广到赫尔德不等式。"),
      T("排序不等式", explain="两组有序数反序和≤乱序和≤同序和。", deriv="由交换调整法。", app="证明对称不等式。", note="等号当且仅当其中一组全相等。", hist="不等式经典。", ext="切比雪夫不等式是其推论。"),
      T("高次不等式穿根法", explain="将高次不等式因式分解后，用数轴穿根法求解。", deriv="由各因式符号变化。", app="解高次不等式。", note="奇穿偶不穿（奇次根穿过，偶次根不穿）。", hist="不等式解法。", ext="数轴标根法。"),
      T("权方和不等式", formula=r"\sum\frac{a_i^{m+1}}{b_i^m}\geq\frac{(\sum a_i)^{m+1}}{(\sum b_i)^m}", explain="Holder不等式的特例。", deriv="由赫尔德不等式。", app="分式不等式、最值。", note="aᵢ,bᵢ>0，m>0。", hist="不等式。", ext="m=1时为柯西分式形式。"),
      T("琴生不等式", explain="凸函数中f((x₁+...+xₙ)/n)≤(f(x₁)+...+f(xₙ))/n。", deriv="由凸函数定义。", app="证明不等式。", note="凹函数不等号反向。", hist="琴生1906年。", ext="加权琴生不等式。"),
      T("反证法证明不等式", explain="假设结论不成立，推出矛盾。", deriv="逻辑反证。", app="不等式证明。", note="适用于存在性、唯一性命题。", hist="证明方法。", ext="与逆否命题等价。"),
      T("数学归纳法证不等式", explain="用归纳法证明与n有关的不等式。", deriv="归纳基础+归纳递推。", app="数列不等式。", note="递推步需灵活放缩。", hist="证明方法。", ext="加强命题再归纳。"),
      T("方程根的分布", explain="二次方程根在指定区间内的条件。", deriv="由二次函数图象和零点定理。", app="确定参数范围。", note="考虑开口、判别式、对称轴、端点函数值。", hist="二次方程。", ext="转化为函数零点问题。"),
      T("超越方程", explain="含指数、对数、三角函数等超越函数的方程。", deriv="无法用代数方法精确求解。", app="数值分析。", note="常用图象法或二分法求近似解。", hist="方程论。", ext="牛顿迭代法求数值解。"),
      T("参数方程", explain="用参数表示曲线上点的坐标。", deriv="引入中间变量t，x=f(t),y=g(t)。", app="解析几何、运动轨迹。", note="消去参数得普通方程。", hist="解析几何。", ext="极坐标方程是特例。"),
      T("方程组的几何意义", explain="方程组的解对应图象的交点。", deriv="由方程与曲线关系。", app="解析几何。", note="无解=平行，无数解=重合。", hist="数形结合。", ext="线性方程组与矩阵。"),
      T("不等式几何意义", explain="不等式表示平面区域。", deriv="由线性规划。", app="线性规划、区域表示。", note="Ax+By+C>0表示直线一侧。", hist="数形结合。", ext="可行域与最优解。"),
    ]},
  ]},
  {"ch":"第二章","title":"函数","en":"FUNCTIONS","sub":"函数概念 · 初等函数 · 函数性质 · 抽象函数 · 数列","desc":"从函数概念到各类初等函数的性质与数列，构建函数论的完整体系。","sections":[
    {"name":"2.1 函数概念与表示","color":"#2563eb","desc":"映射、定义域、值域","topics":[
      T("函数定义", formula=r"f:A\to B,\ x\mapsto y=f(x)", explain="设A,B非空数集，若对A中每个x，按对应法则f，B中都有唯一确定的y与之对应，则f是A到B的函数。", deriv="由映射概念限制到数集。", app="描述变量间依赖关系。", note="函数三要素：定义域、对应法则、值域。", hist="莱布尼茨1673年首次使用function一词。", ext="推广到一般集合上的映射。"),
      T("定义域", explain="函数自变量x的取值集合。", deriv="由实际意义或表达式有意义的条件确定。", app="确定函数研究范围。", note="分母≠0、偶次根号下≥0、对数真数>0等。", hist="函数概念的要素。", ext="自然定义域与实际定义域的区别。"),
      T("值域", explain="函数值y的取值集合。", deriv="由定义域和对应法则确定。", app="了解函数输出范围。", note="值域是B的子集，不一定等于B。", hist="函数概念的要素。", ext="满射时值域=B。"),
      T("对应法则", explain="函数中自变量到因变量的对应规律。", deriv="函数的核心。", app="表示函数关系。", note="相同定义域值域但对应法则不同是不同函数。", hist="函数概念的要素。", ext="对应法则可用解析式、图象、表格表示。"),
      T("函数相等", explain="两个函数相等当且仅当定义域和对应法则都相同。", deriv="由函数三要素，值域由前两者决定。", app="判断函数是否相同。", note="值域相同不一定是同一函数。", hist="函数概念。", ext="函数的同构。"),
      T("区间表示", formula=r"[a,b]=\{x\mid a\leq x\leq b\}", explain="用区间表示数集：闭区间[a,b]、开区间(a,b)、半开半闭、无穷区间。", deriv="由实数的有序性和连通性。", app="简洁表示定义域、值域。", note="注意开闭端点和无穷的写法。", hist="集合表示法。", ext="邻域U(a,δ)=(a-δ,a+δ)。"),
      T("映射", formula=r"f:A\to B", explain="设A,B非空集合，若对A中每个元素，B中都有唯一确定元素与之对应，则f是A到B的映射。", deriv="函数的推广（不限数集）。", app="抽象代数中同态、同构。", note="函数是数集到数集的映射。", hist="函数概念的推广。", ext="单射、满射、双射。"),
      T("单射", formula=r"f(x_1)=f(x_2)\Rightarrow x_1=x_2", explain="若不同原像对应不同像，则f是单射（一一对应）。", deriv="由映射定义加条件。", app="可逆的必要条件。", note="单射才有逆映射（在值域上）。", hist="映射分类。", ext="单射也称嵌入。"),
      T("满射", formula=r"\forall y\in B,\exists x\in A, f(x)=y", explain="若B中每个元素都有原像，则f是满射。", deriv="由映射定义加条件。", app="值域=B。", note="满射的值域等于目标集。", hist="映射分类。", ext="满射也称到上映射。"),
      T("双射", explain="既是单射又是满射的映射。", deriv="单射+满射。", app="存在逆映射。", note="双射建立两集合的一一对应。", hist="映射分类。", ext="双射的逆映射也是双射。"),
      T("函数表示法", explain="解析法、图象法、列表法。", deriv="从不同角度表示函数。", app="根据需要选择表示方法。", note="三种方法各有优劣。", hist="函数表示。", ext="分段函数用解析法分段表示。"),
      T("分段函数", explain="在定义域不同区间上有不同对应法则的函数。", deriv="由实际问题的分段特征。", app="绝对值函数、取整函数等。", note="分段函数是一个函数，不是多个函数。", hist="函数表示。", ext="连续但不可导的典型例子。"),
      T("求函数定义域", explain="使函数解析式有意义的自变量集合。", deriv="根据各运算有意义的条件列不等式组。", app="函数研究的第一步。", note="分式分母≠0，偶次根号下≥0，对数真数>0，零次幂底数≠0。", hist="函数基础。", ext="实际问题还需考虑实际意义。"),
      T("求函数值域", explain="由定义域和对应法则求函数值的集合。", deriv="常用方法：直接法、配方法、换元法、判别式法、单调性法。", app="了解函数取值范围。", note="值域由定义域和对应法则共同决定。", hist="函数基础。", ext="反函数定义域即原函数值域。"),
      T("函数求值", explain="给定x求f(x)或反过来。", deriv="代入对应法则。", app="函数基本运算。", note="注意分段函数要代入对应段。", hist="函数基本操作。", ext="复合函数求值由内到外。"),
    ]},
    {"name":"2.2 初等函数","color":"#7c3aed","desc":"幂、指、对、三角、反三角","topics":[
      T("幂函数", formula=r"y=x^\alpha\ (\alpha\in\mathbb{R})", explain="底数为自变量、指数为常数的函数。", deriv="由幂运算定义。", app="各种物理关系。", note="α不同时定义域、图象差异大；恒过(1,1)。", hist="最基本的函数类之一。", ext="α=0时为y=1(x≠0)。"),
      T("幂函数性质", explain="幂函数y=x^α，α>0时在(0,+∞)递增，α<0时递减。", deriv="由指数函数性质或求导。", app="判断单调性、画图象。", note="α>0时图象过(0,0)和(1,1)；α<0时过(1,1)，以坐标轴为渐近线。", hist="幂函数研究。", ext="第一象限图象必过(1,1)。"),
      T("三角函数", formula=r"y=\sin x,\ y=\cos x,\ y=\tan x", explain="以角为自变量的函数。", deriv="由单位圆或直角三角形定义。", app="周期运动、波动。", note="正弦余弦周期2π，正切周期π。", hist="古代天文学。", ext="欧拉公式统一三角函数与指数函数。"),
      T("反三角函数", formula=r"y=\arcsin x,\ y=\arccos x,\ y=\arctan x", explain="三角函数在主值区间上的反函数。", deriv="限制三角函数到单调区间后取反函数。", app="求角度、解三角方程。", note="注意主值区间。", hist="反三角函数。", ext="反三角恒等式。"),
      T("常数函数", formula="y=c", explain="函数值恒为常数c的函数。", deriv="对应法则不依赖自变量。", app="基准线、常数模型。", note="既是奇函数又是偶函数当且仅当c=0。", hist="最简单的函数。", ext="零函数是特殊的常数函数。"),
      T("一次函数", formula=r"y=kx+b\ (k\neq 0)", explain="最高次为1的多项式函数。", deriv="由多项式定义。", app="线性关系、直线方程。", note="k>0递增，k<0递减；b是y轴截距。", hist="线性函数。", ext="k=0时为常数函数。"),
      T("二次函数", formula=r"y=ax^2+bx+c\ (a\neq 0)", explain="最高次为2的多项式函数，图象是抛物线。", deriv="由多项式定义。", app="最值问题、抛物线运动。", note="顶点(-b/2a, (4ac-b²)/4a)；a>0开口向上有最小值。", hist="圆锥曲线的一种。", ext="二次函数是最简单的非线性函数。"),
      T("反比例函数", formula=r"y=\frac{k}{x}\ (k\neq 0)", explain="形如y=k/x的函数。", deriv="由反比例关系定义。", app="反比关系、双曲线。", note="k>0时图象在一、三象限；k<0时在二、四象限。", hist="反比例关系。", ext="等轴双曲线。"),
      T("对勾函数", formula=r"y=x+\frac{a}{x}\ (a>0)", explain="形如y=x+a/x(a>0)的函数，图象如对勾。", deriv="由均值不等式分析。", app="最值问题。", note="在(0,√a]递减，[√a,+∞)递增；最小值2√a。", hist="典型函数模型。", ext="可推广到y=ax+b/x。"),
      T("初等函数", explain="由基本初等函数（幂、指、对、三角、反三角、常数）经有限次四则运算和复合得到的函数。", deriv="由基本初等函数构造。", app="微积分研究的主要对象。", note="分段函数一般不是初等函数。", hist="函数分类。", ext="初等函数在定义域内连续。"),
      T("绝对值函数", formula="y=|x|", explain="y=|x|的图象是V形折线。", deriv="由绝对值定义。", app="距离、分段。", note="在x=0处连续但不可导。", hist="分段函数原型。", ext="|f(x)|的图象是将f(x)下方部分翻折到上方。"),
      T("取整函数", formula=r"y=[x]=\lfloor x\rfloor", explain="不超过x的最大整数。", deriv="由整数部分定义。", app="计数、离散化。", note="[x]≤x<[x]+1。", hist="高斯函数。", ext="小数部分{x}=x-[x]。"),
      T("符号函数", formula=r"y=sgn(x)=\begin{cases}1, & x>0 \\ 0, & x=0 \\ -1, & x<0\end{cases}", explain="表示x的符号。", deriv="由符号定义。", app="判断正负。", note="|x|=x·sgn(x)。", hist="特殊函数。", ext="不连续函数的例子。"),
      T("狄利克雷函数", formula=r"D(x)=\begin{cases}1, & x\in\mathbb{Q} \\ 0, & x\notin\mathbb{Q}\end{cases}", explain="有理点取1，无理点取0的函数。", deriv="由有理数集定义。", app="反例函数。", note="处处不连续，处处不可导。", hist="狄利克雷构造。", ext="没有最小正周期的周期函数。"),
      T("双曲函数", formula=r"\sinh x=\frac{e^x-e^{-x}}{2},\ \cosh x=\frac{e^x+e^{-x}}{2}", explain="由指数函数定义的双曲正弦、余弦。", deriv="由eˣ和e⁻ˣ组合。", app="悬链线、相对论。", note="cosh²x-sinh²x=1。", hist="双曲几何。", ext="与三角函数形式相似。"),
      T("反双曲函数", formula=r"\text{arsinh}\,x=\ln(x+\sqrt{x^2+1})", explain="双曲函数的反函数。", deriv="由反函数求解。", app="积分计算。", note="arsinh定义域R。", hist="反双曲函数。", ext="用对数表示。"),
      T("幂指函数", formula="y=x^x", explain="底数和指数都是自变量的函数。", deriv="取对数法求导：lny=xlnx。", app="优化问题。", note="x>0时定义。", hist="特殊函数。", ext="最小值在x=1/e处。"),
    ]},
    {"name":"2.3 函数性质","color":"#0f766e","desc":"单调、有界、周期、奇偶","topics":[
      T("单调性定义", explain="若对区间I内任意x₁<x₂，都有f(x₁)<f(x₂)，则f在I上递增。", deriv="由函数值随自变量增大的变化趋势定义。", app="判断函数增减、求值域。", note="递增/递减统称单调；严格单调才有反函数。", hist="函数基本性质。", ext="单调函数几乎处处可导（勒贝格定理）。"),
      T("单调性证明", explain="用定义法（作差比较）或导数法证明单调性。", deriv="定义法：f(x₁)-f(x₂)与0比较；导数法：f'(x)>0则递增。", app="证明函数单调。", note="定义法对一切函数适用，导数法只对可导函数。", hist="单调性证明。", ext="复合函数单调性：同增异减。"),
      T("单调区间", explain="函数在其上单调的区间。", deriv="由单调性定义确定。", app="分析函数变化趋势。", note="一个函数可有多个单调区间，不能用∪连接。", hist="函数分析。", ext="单调区间端点根据定义域确定。"),
      T("最值", formula=r"f(x_0)\geq f(x)\ \forall x", explain="函数在定义域或区间上的最大值和最小值。", deriv="由单调性和端点值确定。", app="优化问题。", note="最值是全局概念，极值是局部概念。", hist="极值问题。", ext="闭区间上连续函数必有最值（最值定理）。"),
      T("极值", explain="在某点附近函数值最大（小）的叫极大（小）值。", deriv="由局部比较定义。", app="优化问题。", note="极值是局部概念，极大值不一定大于极小值。", hist="微积分核心概念。", ext="费马定理：极值点处导数为0（若可导）。"),
      T("奇偶性定义", formula=r"f(-x)=f(x)\text{偶},\ f(-x)=-f(x)\text{奇}", explain="偶函数关于y轴对称，奇函数关于原点对称。", deriv="由对称性定义。", app="简化函数分析、积分计算。", note="定义域必须关于原点对称。", hist="函数对称性。", ext="奇×奇=偶，奇×偶=奇，偶×偶=偶。"),
      T("奇偶性判断", explain="先看定义域是否关于原点对称，再验证f(-x)与f(x)的关系。", deriv="由定义。", app="判断函数奇偶性。", note="f(-x)=f(x)偶，f(-x)=-f(x)奇，否则非奇非偶。", hist="函数性质。", ext="任一函数可分解为奇函数+偶函数。"),
      T("奇偶函数运算", formula=r"奇\pm奇=奇,\ 偶\pm偶=偶", explain="奇偶函数的和差积商的奇偶性。", deriv="由定义直接验证。", app="快速判断复合函数奇偶性。", note="奇±奇=奇，偶±偶=偶，奇×奇=偶，奇×偶=奇，偶×偶=偶。", hist="函数性质。", ext="类似奇偶函数的复合。"),
      T("周期性定义", formula="f(x+T)=f(x)", explain="若存在非零常数T，使f(x+T)=f(x)对定义域内所有x成立，则f是周期函数，T是周期。", deriv="由函数值的重复规律定义。", app="描述周期运动。", note="若T是周期则kT(k∈Z,k≠0)也是周期；最小正周期叫基本周期。", hist="周期现象的数学描述。", ext="非常数连续周期函数必有最小正周期（狄利克雷函数除外）。"),
      T("周期函数性质", explain="周期函数的图象每隔一个周期重复。", deriv="由周期性定义。", app="简化周期函数研究（只需研究一个周期）。", note="周期函数定义域至少一侧无界。", hist="周期函数。", ext="两个周期函数之和不一定是周期函数（周期不可公度时）。"),
      T("有界性定义", formula=r"|f(x)|\leq M", explain="若存在M>0使对定义域内所有x有|f(x)|≤M，则f有界。", deriv="由函数值的范围定义。", app="判断函数是否有界。", note="有界⟺有上界且有下界。", hist="有界性。", ext="闭区间上连续函数必有界（有界性定理）。"),
      T("对称性", explain="函数图象的对称性质：关于y轴、原点、直线x=a等。", deriv="由坐标变换验证。", app="利用对称性简化研究。", note="f(a+x)=f(a-x)⟺关于x=a对称。", hist="几何性质。", ext="中心对称与轴对称的判定。"),
      T("函数图象平移", formula="y=f(x-h)+k", explain="y=f(x)向右平移h、向上平移k得到y=f(x-h)+k。", deriv="由坐标变换。", app="函数图象绘制。", note="左加右减，上加下减。", hist="图象变换。", ext="h,k可正可负。"),
      T("函数图象伸缩", formula=r"y=f(ax),\ y=bf(x)", explain="y=f(x)横向伸缩a倍得y=f(ax)，纵向伸缩b倍得y=bf(x)。", deriv="由坐标缩放。", app="函数图象绘制。", note="a>1横向压缩，0<a<1横向拉伸。", hist="图象变换。", ext="与周期、振幅相关。"),
      T("函数图象对称变换", formula=r"y=f(-x),\ y=-f(x)", explain="y=f(-x)关于y轴对称，y=-f(x)关于x轴对称。", deriv="由坐标反射。", app="函数图象绘制。", note="y=-f(-x)关于原点对称。", hist="图象变换。", ext="奇偶函数的对称性即此。"),
      T("二次函数最值", formula=r"y_{\text{最值}}=\frac{4ac-b^2}{4a}", explain="二次函数在顶点处取最值。", deriv="由配方法y=a(x+b/2a)²+(4ac-b²)/4a。", app="最值问题。", note="a>0时取最小值，a<0时取最大值。", hist="二次函数。", ext="在闭区间上需比较端点和顶点。"),
      T("二次函数零点", formula=r"x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}", explain="二次函数与x轴交点的横坐标。", deriv="令y=0解二次方程。", app="求零点、画图象。", note="Δ>0两个零点，Δ=0一个，Δ<0无实零点。", hist="二次函数。", ext="零点即对应方程的根。"),
      T("二次函数对称轴", formula=r"x=-\frac{b}{2a}", explain="二次函数图象的对称轴。", deriv="由配方法或顶点横坐标。", app="分析二次函数。", note="对称轴处取最值。", hist="二次函数。", ext="关于对称轴对称的点函数值相等。"),
      T("函数零点存在定理", explain="若f在[a,b]连续且f(a)·f(b)<0，则在(a,b)内至少有一个零点。", deriv="由介值定理。", app="判断零点存在、二分法求根。", note="是充分条件非必要条件。", hist="连续函数性质。", ext="二分法求方程近似解。"),
      T("函数图象平移变换", formula=r"y=f(x)\to y=f(x-a)+b", explain="向右平移a个单位，向上平移b个单位。", deriv="由坐标变换。", app="画函数图象。", note="左加右减，上加下减。", hist="图象变换。", ext="注意平移方向与符号。"),
      T("函数图象伸缩变换", formula=r"y=f(x)\to y=Af(\omega x)", explain="纵坐标伸缩A倍，横坐标伸缩1/ω倍。", deriv="由坐标变换。", app="画函数图象。", note="A>1纵向拉伸，ω>1横向压缩。", hist="图象变换。", ext="三角函数的振幅和周期。"),
      T("反函数性质", explain="y=f⁻¹(x)与y=f(x)关于y=x对称。", deriv="由反函数定义。", app="求反函数、对数与指数互化。", note="定义域与值域互换；单调函数才有反函数。", hist="函数理论。", ext="f(f⁻¹(x))=x。"),
      T("复合函数单调性", explain="同增异减原则：内外函数单调性相同则增，不同则减。", deriv="由单调性定义逐层分析。", app="判断复合函数单调区间。", note="注意定义域。", hist="复合函数。", ext="多层复合逐层判断。"),
      T("复合函数定义域", explain="内层函数的值域须落在外层函数定义域内。", deriv="由复合函数定义。", app="求复合函数定义域。", note="y=f(g(x))需g(x)∈D_f。", hist="函数理论。", ext="定义域是x的范围。"),
      T("函数值域求法", explain="观察法、配方法、换元法、判别式法、单调性法等。", deriv="由函数性质。", app="求函数值域。", note="先求定义域。", hist="函数分析。", ext="复杂函数可用导数。"),
    ]},
    {"name":"2.4 抽象函数与复合函数","color":"#c2410c","desc":"无解析式函数、复合","topics":[
      T("抽象函数", explain="没有给出具体解析式，只给出某些性质（如f(x+y)=f(x)+f(y)）的函数。", deriv="由函数方程定义。", app="函数方程、函数性质研究。", note="常见模型：f(x+y)=f(x)+f(y)对应正比例函数。", hist="柯西方程等函数方程。", ext="不连续解需选择公理。"),
      T("柯西方程", formula="f(x+y)=f(x)+f(y)", explain="满足f(x+y)=f(x)+f(y)的函数方程。", deriv="若f连续则f(x)=kx。", app="抽象函数的原型。", note="连续/单调/有界条件下解为f(x)=kx。", hist="柯西1821年研究。", ext="无连续性条件有野生解。"),
      T("指数型抽象函数", formula="f(x+y)=f(x)f(y)", explain="满足f(x+y)=f(x)f(y)的函数，对应指数函数。", deriv="若f连续且不恒为0，则f(x)=aˣ。", app="抽象函数模型。", note="f(0)=1，f(x)>0。", hist="指数函数的函数方程刻画。", ext="f(x)≡0也是解。"),
      T("对数型抽象函数", formula="f(xy)=f(x)+f(y)", explain="满足f(xy)=f(x)+f(y)的函数，对应对数函数。", deriv="若f连续且在(0,+∞)上，则f(x)=k·lnx。", app="抽象函数模型。", note="f(1)=0。", hist="对数函数的函数方程刻画。", ext="f在0处无定义。"),
      T("复合函数", formula="y=f(g(x))", explain="若y=f(u),u=g(x)，则y=f(g(x))叫复合函数，u为中间变量。", deriv="函数的复合运算。", app="复杂函数的分解与合成。", note="内层值域与外层定义域的交集非空才能复合。", hist="函数复合。", ext="复合函数定义域是使g(x)在f定义域内的x集合。"),
      T("复合函数奇偶性", explain="复合函数奇偶性：内层偶则复合偶；内层奇则与外层奇偶性相同。", deriv="由定义验证。", app="判断复合函数奇偶性。", note="g偶⇒f(g(x))偶；g奇⇒f(g(x))的奇偶性与f相同。", hist="复合函数性质。", ext="多层复合的奇偶性判断。"),
      T("反函数", formula="y=f^{-1}(x)", explain="若函数f是双射，则其逆映射叫f的反函数。", deriv="由逆映射定义。", app="求反函数、指数对数互化。", note="原函数与反函数图象关于y=x对称。", hist="反函数概念。", ext="严格单调函数必有反函数。"),
      T("求反函数步骤", explain="1.由y=f(x)解出x=f⁻¹(y)；2.交换x,y得y=f⁻¹(x)；3.注明定义域（原函数值域）。", deriv="由反函数定义。", app="求反函数。", note="注意反函数的定义域是原函数的值域。", hist="反函数求法。", ext="分段函数求反函数要分段处理。"),
      T("隐函数", explain="未显式解出y的函数关系F(x,y)=0。", deriv="由方程定义的函数关系。", app="圆锥曲线方程、隐函数求导。", note="一个方程可能确定多个隐函数。", hist="函数概念推广。", ext="隐函数存在定理。"),
      T("参数方程表示函数", formula=r"\begin{cases}x=\varphi(t)\\y=\psi(t)\end{cases}", explain="用参数t表示x,y的函数关系。", deriv="消去参数得普通方程。", app="运动轨迹、曲线参数化。", note="参数方程可表示非函数曲线。", hist="解析几何。", ext="参数方程求导。"),
      T("函数渐近线", explain="函数图象无限接近的直线。", deriv="由极限行为分析。", app="画函数图象。", note="分水平、垂直、斜渐近线三类。", hist="函数图象分析。", ext="斜渐近线y=kx+b由极限求。"),
      T("函数凸性", explain="函数图象的凹凸方向。", deriv="由二阶导数符号判断（预备知识）。", app="不等式、优化。", note="凸函数满足f((x₁+x₂)/2)≤(f(x₁)+f(x₂))/2。", hist="凸分析。", ext="琴生不等式的基础。"),
      T("函数拐点", explain="函数图象凹凸改变的点。", deriv="二阶导数为零且变号的点。", app="画函数图象。", note="拐点处二阶导数为零或不存在。", hist="曲线分析。", ext="与极值点的区别。"),
      T("隐函数存在性", explain="F(x,y)=0在一定条件下能确定y=f(x)。", deriv="由隐函数定理（偏导连续且F_y≠0）。", app="曲线方程、求导。", note="隐函数不一定能显式解出。", hist="隐函数定理。", ext="多元隐函数组。"),
      T("极坐标方程", formula=r"x=r\cos\theta,\ y=r\sin\theta", explain="用极坐标(r,θ)表示平面上的点。", deriv="由三角函数定义。", app="对称图形、积分。", note="极坐标与直角坐标可互换。", hist="牛顿引入。", ext="极坐标方程求导。"),
      T("极坐标与直角坐标转换", formula=r"r=\sqrt{x^2+y^2},\ \theta=\arctan\frac{y}{x}", explain="极坐标与直角坐标的互换公式。", deriv="由直角三角形边角关系。", app="坐标系转换。", note="注意象限对θ的影响。", hist="解析几何。", ext="柱坐标、球坐标。"),
      T("函数交点", explain="两函数图象交点对应方程f(x)=g(x)的解。", deriv="令f(x)=g(x)求解。", app="求图象交点。", note="交点个数=方程实根个数。", hist="数形结合。", ext="超越方程图象法求解。"),
    ]},
    {"name":"2.5 数列","color":"#7c3aed","desc":"等差、等比、求和","topics":[
      T("数列定义", formula=r"\{a_n\},\ a_n=f(n)", explain="按一定次序排列的一列数，可看作定义在正整数集上的函数。", deriv="由函数概念限制到正整数集。", app="描述离散变化、求和。", note="数列有穷或无穷；有序列。", hist="离散数学基础。", ext="数列的极限是微积分的入口。"),
      T("数列通项公式", formula="a_n=f(n)", explain="数列第n项与n的关系式。", deriv="由数列规律归纳。", app="求数列任意项。", note="并非所有数列都有通项公式。", hist="数列表示。", ext="递推公式也是表示数列的方法。"),
      T("数列前n项和", formula=r"S_n=a_1+a_2+\cdots+a_n", explain="数列前n项之和。", deriv="由加法定义。", app="求和问题。", note="aₙ=Sₙ-Sₙ₋₁(n≥2)，a₁=S₁。", hist="数列求和。", ext="级数的部分和。"),
      T("等差数列", formula="a_n=a_1+(n-1)d", explain="从第二项起，每一项与前一项的差为常数d的数列。", deriv="由公差d递推：aₙ=aₙ₋₁+d。", app="均匀变化的量。", note="d>0递增，d<0递减，d=0常数列。", hist="古代已有等差求和。", ext="等差数列的和公式。"),
      T("等差数列求和", formula=r"S_n=\frac{n(a_1+a_n)}{2}=na_1+\frac{n(n-1)}{2}d", explain="等差数列前n项和公式。", deriv="倒序相加法：Sₙ=a₁+...+aₙ，Sₙ=aₙ+...+a₁，相加得2Sₙ=n(a₁+aₙ)。", app="求和。", note="也可用首项末项平均值×项数。", hist="高斯少年时巧妙求和。", ext="Sₙ是关于n的二次函数（d≠0时）。"),
      T("等差中项", formula=r"A=\frac{a+b}{2}", explain="a,A,b成等差数列，则A叫a,b的等差中项。", deriv="由A-a=b-A得2A=a+b。", app="等差数列性质。", note="a,b的等差中项即平均值。", hist="中项概念。", ext="推广到n个数的等差中项。"),
      T("等差数列性质", explain="等差数列中，若m+n=p+q，则aₘ+aₙ=aₚ+a_q。", deriv="由通项公式直接验证。", app="简化计算。", note="下标和相等则项和相等。", hist="数列性质。", ext="等比数列有类似积的性质。"),
      T("等比数列", formula="a_n=a_1q^{n-1}", explain="从第二项起，每一项与前一项的比为常数q的数列。", deriv="由公比q递推：aₙ=aₙ₋₁·q。", app="指数增长/衰减、复利。", note="a₁≠0,q≠0；q>0各项同号。", hist="古代已有等比数列。", ext="等比数列求和。"),
      T("等比数列求和", formula=r"S_n=\frac{a_1(1-q^n)}{1-q}\ (q\neq 1)", explain="等比数列前n项和公式。", deriv="错位相减法：Sₙ=a₁+a₁q+...+a₁qⁿ⁻¹，qSₙ=a₁q+...+a₁qⁿ，相减得(1-q)Sₙ=a₁(1-qⁿ)。", app="求和。", note="q=1时Sₙ=na₁。", hist="等比求和。", ext="|q|<1时无穷等比级数和为a₁/(1-q)。"),
      T("等比中项", formula=r"G=\pm\sqrt{ab}", explain="a,G,b成等比数列，则G叫a,b的等比中项。", deriv="由G/a=b/G得G²=ab。", app="等比数列性质。", note="a,b同号时等比中项存在且有两个。", hist="中项概念。", ext="几何平均即等比中项（非负）。"),
      T("等比数列性质", explain="等比数列中，若m+n=p+q，则aₘ·aₙ=aₚ·a_q。", deriv="由通项公式验证。", app="简化计算。", note="下标和相等则项积相等。", hist="数列性质。", ext="与等差数列的和性质对应。"),
      T("数列求和方法", explain="公式法、倒序相加、错位相减、裂项相消、分组求和。", deriv="根据数列特点选择方法。", app="各类数列求和。", note="等差用公式/倒序相加，等比用公式/错位相减，1/[n(n+1)]用裂项。", hist="求和技巧。", ext="复杂数列需灵活组合方法。"),
      T("裂项相消", formula=r"\frac{1}{n(n+1)}=\frac{1}{n}-\frac{1}{n+1}", explain="将通项拆成两项之差，求和时中间项抵消。", deriv="通分验证。", app="分式数列求和。", note="关键是正确裂项。", hist="求和技巧。", ext="推广到1/[n(n+k)]=1/k·(1/n-1/(n+k))。"),
      T("错位相减", explain="适用于等差数列×等比数列的求和。", deriv="乘以公比后错位相减。", app="等差×等比数列求和。", note="计算时注意项数和符号。", hist="求和技巧。", ext="等比数列求和即错位相减的特例。"),
      T("数列递推", formula="a_{n+1}=f(a_n)", explain="用递推关系定义的数列。", deriv="由前项求后项。", app="递推数列。", note="需要初始条件。", hist="递推是定义数列的重要方式。", ext="线性递推数列（斐波那契等）。"),
      T("斐波那契数列", formula=r"F_n=F_{n-1}+F_{n-2},\ F_1=F_2=1", explain="从第三项起每项等于前两项之和的数列。", deriv="由递推关系定义。", app="自然生长、黄金分割。", note="1,1,2,3,5,8,13,21,...", hist="斐波那契1202年研究兔子繁殖。", ext="通项可用黄金分割比表示。"),
      T("等差数列判定", explain="证明数列是等差数列的方法：定义法(aₙ₊₁-aₙ=d)、中项法(2aₙ₊₁=aₙ+aₙ₊₂)。", deriv="由等差数列定义。", app="判断数列类型。", note="两种方法等价。", hist="数列判定。", ext="等比数列类似判定。"),
      T("等比数列判定", explain="证明数列是等比数列的方法：定义法(aₙ₊₁/aₙ=q)、中项法(aₙ₊₁²=aₙ·aₙ₊₂)。", deriv="由等比数列定义。", app="判断数列类型。", note="注意各项非零。", hist="数列判定。", ext="与等差数列判定对偶。"),
      T("数列通项求法", explain="求数列通项的方法：观察法、累加累乘法、构造法、数学归纳法。", deriv="根据递推关系特点选择。", app="由递推求通项。", note="aₙ₊₁=aₙ+f(n)用累加，aₙ₊₁=aₙ·f(n)用累乘。", hist="数列方法。", ext="特征方程法解线性递推。"),
      T("累加求通项", formula=r"a_n=a_1+\sum_{k=1}^{n-1}(a_{k+1}-a_k)", explain="对aₙ₊₁-aₙ=f(n)型递推，累加求通项。", deriv="aₙ=a₁+(a₂-a₁)+(a₃-a₂)+...+(aₙ-aₙ₋₁)。", app="求递推数列通项。", note="需已知a₁。", hist="递推解法。", ext="对应离散微积分。"),
      T("累乘求通项", formula=r"a_n=a_1\cdot\prod_{k=1}^{n-1}\frac{a_{k+1}}{a_k}", explain="对aₙ₊₁/aₙ=f(n)型递推，累乘求通项。", deriv="aₙ=a₁·(a₂/a₁)·(a₃/a₂)·...·(aₙ/aₙ₋₁)。", app="求递推数列通项。", note="需已知a₁。", hist="递推解法。", ext="与累加法对偶。"),
      T("构造法求通项", explain="对非线性递推，通过变形构造等差或等比数列。", deriv="如aₙ₊₁=paₙ+q，设aₙ₊₁+c=p(aₙ+c)构造等比。", app="求复杂递推通项。", note="关键是正确构造辅助数列。", hist="递推技巧。", ext="特征方程法的特例。"),
      T("数列极限概念", formula=r"\lim_{n\to\infty}a_n=A", explain="当n无限增大时，aₙ无限趋近于常数A。", deriv="由ε-N定义严格描述。", app="微积分基础。", note="极限存在则数列收敛，否则发散。", hist="分析严格化。", ext="数列极限是函数极限的基础。"),
      T("特征方程法", explain="对aₙ₊₂=paₙ₊₁+qaₙ型递推，解特征方程x²=px+q。", deriv="设aₙ=xⁿ代入递推得特征方程。", app="二阶线性递推求通项。", note="两根不等时aₙ=Ax₁ⁿ+Bx₂ⁿ。", hist="线性递推。", ext="重根时aₙ=(A+Bn)xⁿ。"),
      T("不动点法求通项", explain="对aₙ₊₁=f(aₙ)，求f(x)=x的不动点构造辅助数列。", deriv="不动点处递推可线性化。", app="分式线性递推。", note="f(x)=(ax+b)/(cx+d)型常用。", hist="迭代理论。", ext="与特征方程法相关。"),
      T("数学归纳法", explain="证明与正整数有关的命题的方法。", deriv="归纳基础+归纳递推。", app="数列命题、整除性证明。", note="两步缺一不可。", hist="皮亚诺公理。", ext="第二数学归纳法、反向归纳法。"),
      T("倒序相加求和", explain="将数列倒序后与原式相加，利用对称性求和。", deriv="如等差数列求和。", app="等差数列、组合数求和。", note="高斯求和法。", hist="等差数列求和。", ext="C(n,k)的求和常用。"),
      T("错位相减求和", explain="等差×等比型数列求和方法。", deriv="Sₙ减去qSₙ错位相减。", app="aₙ=(an+b)qⁿ型求和。", note="注意项数和系数。", hist="数列求和。", ext="乘公比错位相减。"),
      T("裂项相消求和", explain="将通项拆成两项之差，求和时中间项抵消。", deriv="如1/[n(n+1)]=1/n-1/(n+1)。", app="分式数列求和。", note="关键是正确裂项。", hist="数列求和。", ext="根式、阶乘型也可裂项。"),
      T("分组求和法", explain="将数列分成若干组分别求和。", deriv="如奇数项和偶数项分组。", app="周期数列、分段数列求和。", note="根据规律合理分组。", hist="数列求和。", ext="与并项求和类似。"),
      T("数列与函数关系", explain="数列是定义在正整数集上的特殊函数。", deriv="aₙ=f(n)。", app="用函数观点研究数列。", note="数列的单调性即函数单调性。", hist="函数与数列。", ext="数列极限与函数极限联系。"),
    ]},
  ]},
  {"ch":"第三章","title":"几何","en":"GEOMETRY","sub":"向量 · 平面几何 · 立体几何 · 解析几何","desc":"从向量到平面、立体、解析几何，构建完整的几何体系。","sections":[
    {"name":"3.1 平面向量","color":"#2563eb","desc":"向量运算、数量积","topics":[
      T("向量定义", explain="既有大小又有方向的量。", deriv="区别于只有大小的标量。", app="力、速度、位移等。", note="向量可用有向线段表示，与起点无关（自由向量）。", hist="向量概念由力学引入。", ext="推广到n维向量。"),
      T("向量的模", formula=r"|\vec{a}|", explain="向量的大小（长度）。", deriv="有向线段的长度。", app="计算向量长度。", note="|a|≥0；|a|=0⟺a是零向量。", hist="向量的数量特征。", ext="推广到向量范数。"),
      T("零向量", formula=r"\vec{0}", explain="长度为0的向量，方向任意。", deriv="由模为零定义。", app="向量运算的单位元。", note="零向量与任意向量平行；注意与实数0的区别。", hist="向量代数。", ext="向量空间的零元。"),
      T("单位向量", formula=r"|\vec{a}|=1", explain="长度为1的向量。", deriv="由模为1定义。", app="表示方向。", note="与a同向的单位向量为a/|a|。", hist="方向的标准化表示。", ext="标准基向量是特殊单位向量。"),
      T("相等向量", explain="长度相等且方向相同的向量。", deriv="由模和方向同时相等。", app="向量比较。", note="与起点位置无关。", hist="自由向量的性质。", ext="向量空间的元素相等。"),
      T("相反向量", explain="长度相等方向相反的向量。", deriv="由负向量定义。", app="向量减法。", note="a的相反向量是-a。", hist="向量代数。", ext="加法逆元。"),
      T("共线向量", explain="方向相同或相反的非零向量，也叫平行向量。", deriv="由方向关系定义。", app="判断向量平行。", note="零向量与任意向量共线。", hist="向量关系。", ext="两向量共线⟺存在λ使a=λb。"),
      T("向量加法", formula=r"\vec{a}+\vec{b}", explain="向量加法满足三角形法则或平行四边形法则。", deriv="几何作图或坐标运算。", app="力的合成、位移合成。", note="满足交换律和结合律。", hist="由平行四边形法则确立。", ext="向量空间的加法。"),
      T("三角形法则", explain="首尾相接：将b的起点移到a的终点，则从a起点到b终点的向量为a+b。", deriv="几何作图。", app="向量加法。", note="适用于多个向量相加（多边形法则）。", hist="向量加法。", ext="推广到n个向量。"),
      T("平行四边形法则", explain="共起点：以a,b为邻边作平行四边形，对角线向量为a+b。", deriv="几何作图。", app="力的合成。", note="三角形法则和平行四边形法则等价。", hist="力的平行四边形法则。", ext="仅适用于两个向量。"),
      T("向量减法", formula=r"\vec{a}-\vec{b}=\vec{a}+(-\vec{b})", explain="向量减法等于加上相反向量。", deriv="由加法和负向量。", app="向量运算。", note="几何上：a-b是从b终点指向a终点的向量（共起点时）。", hist="向量代数。", ext="向量空间的减法。"),
      T("数乘向量", formula=r"\lambda\vec{a}", explain="实数λ与向量a的乘积，长度为|λ||a|，方向：λ>0同向，λ<0反向。", deriv="由缩放定义。", app="向量缩放、共线判断。", note="λ=0时为零向量。", hist="向量代数。", ext="向量空间的数乘。"),
      T("向量共线定理", formula=r"\vec{b}=\lambda\vec{a}\ (\vec{a}\neq\vec{0})", explain="向量b与非零向量a共线当且仅当存在唯一实数λ使b=λa。", deriv="由共线定义和数乘。", app="判断共线、求参数。", note="a≠0是条件。", hist="向量代数基本定理。", ext="推广到三维。"),
      T("平面向量基本定理", formula=r"\vec{a}=\lambda_1\vec{e_1}+\lambda_2\vec{e_2}", explain="若e₁,e₂不共线，则平面内任一向量a可唯一表示为a=λ₁e₁+λ₂e₂。", deriv="由平行四边形法则分解。", app="建立坐标系、向量分解。", note="e₁,e₂叫一组基底。", hist="向量坐标化的基础。", ext="推广到n维空间的基。"),
      T("向量坐标", formula=r"\vec{a}=(x,y)", explain="在直角坐标系中，向量a=xi+yj，记作(x,y)。", deriv="由基本定理取i,j为基底。", app="向量运算坐标化。", note="坐标等于终点坐标减起点坐标。", hist="向量代数与解析几何结合。", ext="推广到n维坐标向量。"),
      T("向量坐标运算", formula=r"(x_1,y_1)\pm(x_2,y_2)=(x_1\pm x_2, y_1\pm y_2)", explain="向量加减对应坐标加减，数乘对应坐标数乘。", deriv="由基本定理和运算律。", app="向量计算。", note="坐标运算使向量代数化。", hist="坐标法。", ext="推广到n维。"),
      T("数量积", formula=r"\vec{a}\cdot\vec{b}=|\vec{a}||\vec{b}|\cos\theta", explain="向量a,b的数量积（点积）等于模长乘积乘夹角余弦。", deriv="由投影定义。", app="求夹角、判断垂直、物理做功。", note="数量积是标量；a·a=|a|²。", hist="向量代数。", ext="推广到内积空间。"),
      T("数量积坐标公式", formula=r"\vec{a}\cdot\vec{b}=x_1x_2+y_1y_2", explain="坐标形式的数量积等于对应坐标乘积之和。", deriv="由i·i=j·j=1,i·j=0展开。", app="计算数量积。", note="是计算夹角和模的基础。", hist="坐标法。", ext="推广到n维：a·b=Σxᵢyᵢ。"),
      T("向量垂直", formula=r"\vec{a}\perp\vec{b}\Leftrightarrow\vec{a}\cdot\vec{b}=0", explain="两非零向量垂直当且仅当数量积为零。", deriv="由a·b=|a||b|cosθ，θ=90°时cosθ=0。", app="判断垂直。", note="对零向量另行约定。", hist="垂直判定。", ext="内积空间中正交的定义。"),
      T("向量夹角", formula=r"\cos\theta=\frac{\vec{a}\cdot\vec{b}}{|\vec{a}||\vec{b}|}", explain="两向量夹角由数量积与模的比值确定。", deriv="由数量积定义反解cosθ。", app="求两向量夹角。", note="θ∈[0,π]。", hist="向量几何。", ext="高维空间中夹角的定义。"),
      T("向量投影", formula=r"\text{proj}_{\vec{b}}\vec{a}=\frac{\vec{a}\cdot\vec{b}}{|\vec{b}|}", explain="向量a在b方向上的投影数量。", deriv="由|a|cosθ=|a||b|cosθ/|b|=a·b/|b|。", app="分解向量、物理计算。", note="投影是数量（可正可负）。", hist="向量几何。", ext="投影向量为proj·(b/|b|)。"),
      T("向量模的计算", formula=r"|\vec{a}|=\sqrt{x^2+y^2}", explain="向量的模等于坐标平方和的平方根。", deriv="由a·a=x²+y²=|a|²。", app="求向量长度。", note="即两点间距离。", hist="距离公式。", ext="推广到n维欧氏范数。"),
    ]},
    {"name":"3.2 平面几何","color":"#7c3aed","desc":"三角形、圆、多边形","topics":[
      T("三角形分类", explain="按角分：锐角、直角、钝角三角形；按边分：不等边、等腰、等边三角形。", deriv="由角和边的特征分类。", app="三角形研究。", note="等边是特殊的等腰。", hist="几何基本分类。", ext="球面三角形分类不同。"),
      T("三角形内角和", formula=r"A+B+C=180^\circ", explain="三角形三个内角之和为180°。", deriv="过一顶点作对边平行线，利用平行线内错角相等。", app="求三角形内角。", note="是欧氏几何的基本定理，依赖平行公理。", hist="欧几里得证明。", ext="非欧几何中内角和≠180°。"),
      T("三角形外角", formula=r"\text{外角}=\text{不相邻两内角和}", explain="三角形的一个外角等于与它不相邻的两个内角之和。", deriv="由内角和与邻补角关系。", app="求角度。", note="外角大于任一不相邻内角。", hist="外角定理。", ext="多边形外角和恒为360°。"),
      T("三角形三边关系", formula="a+b>c", explain="三角形任意两边之和大于第三边，任意两边之差小于第三边。", deriv="两点之间线段最短。", app="判断三边能否构成三角形。", note="a-b<c<a+b。", hist="几何不等关系。", ext="是三角形存在的充要条件。"),
      T("等腰三角形性质", explain="等腰三角形两底角相等，顶角平分线、底边上的中线、高互相重合（三线合一）。", deriv="作底边上的高，证明两三角形全等。", app="等腰三角形计算。", note="等边对等角，等角对等边。", hist="古希腊几何。", ext="等腰三角形是轴对称图形。"),
      T("等边三角形性质", explain="等边三角形三边相等，三个内角都是60°。", deriv="三边相等→三角相等→各60°。", app="正三角形计算。", note="有一个角为60°的等腰三角形是等边三角形。", hist="正多边形的特例。", ext="等边三角形是最对称的三角形。"),
      T("直角三角形性质", formula="a^2+b^2=c^2", explain="直角三角形两直角边平方和等于斜边平方（勾股定理）。", deriv="面积法或相似三角形。", app="求边长、判断直角。", note="斜边最长；斜边中线等于斜边一半。", hist="商高、毕达哥拉斯。", ext="勾股数组的通解。"),
      T("勾股定理", formula="a^2+b^2=c^2", explain="直角三角形两直角边平方和等于斜边平方。", deriv="多种证法：赵爽弦图、面积拼接、相似三角形。", app="求距离、判断直角三角形。", note="逆定理也成立：若a²+b²=c²则为直角三角形。", hist="中国商高、古希腊毕达哥拉斯分别发现。", ext="费马大定理是其推广（n>2时无正整数解）。"),
      T("三角形全等", explain="能够完全重合的两个三角形全等。", deriv="由重合定义。", app="证明线段相等、角相等。", note="全等三角形对应边相等、对应角相等。", hist="几何证明基础。", ext="SSS,SAS,ASA,AAS,HL判定。"),
      T("全等判定SSS", explain="三边对应相等的两个三角形全等。", deriv="由三角形的确定性。", app="证明三角形全等。", note="是三角形稳定性的体现。", hist="欧几里得几何。", ext="是最基本的全等判定。"),
      T("全等判定SAS", explain="两边及其夹角对应相等的两个三角形全等。", deriv="由夹角确定形状。", app="证明全等。", note="必须是夹角，SSA不能判定。", hist="欧几里得几何。", ext="两边一对角（SSA）一般不能判定全等。"),
      T("全等判定ASA/AAS", explain="两角及其夹边（或对边）对应相等的两个三角形全等。", deriv="由三角形内角和确定第三角。", app="证明全等。", note="ASA是夹边，AAS是对边。", hist="欧几里得几何。", ext="由内角和定理AAS可转化为ASA。"),
      T("直角三角形全等HL", explain="斜边和一条直角边对应相等的两个直角三角形全等。", deriv="由勾股定理确定第三边，转化为SSS。", app="证明直角三角形全等。", note="仅适用于直角三角形。", hist="特殊全等判定。", ext="是SSA在直角三角形中的特例。"),
      T("三角形相似", explain="对应角相等、对应边成比例的两个三角形相似。", deriv="由相似定义。", app="求比例、测量。", note="相似比k，面积比k²。", hist="相似图形。", ext="相似变换是保角变换。"),
      T("相似判定AA", explain="两角对应相等的两个三角形相似。", deriv="第三角必相等，由内角和。", app="证明相似。", note="最常用的相似判定。", hist="相似几何。", ext="类似全等的AAS。"),
      T("相似判定SAS", explain="两边对应成比例且夹角相等的两个三角形相似。", deriv="由比例和夹角确定形状。", app="证明相似。", note="必须是夹角。", hist="相似几何。", ext="与全等SAS对应。"),
      T("相似判定SSS", explain="三边对应成比例的两个三角形相似。", deriv="由比例确定形状。", app="证明相似。", note="比例相等即可。", hist="相似几何。", ext="与全等SSS对应。"),
      T("三角形中位线", formula=r"\text{中位线}\parallel\text{第三边},\ \text{且}=\frac{1}{2}\text{第三边}", explain="连接三角形两边中点的线段平行于第三边且等于第三边的一半。", deriv="构造平行四边形或用相似证明。", app="证明平行、求长度。", note="中位线定理。", hist="几何定理。", ext="推广到梯形中位线。"),
      T("角平分线定理", formula=r"\frac{AB}{AC}=\frac{BD}{DC}", explain="三角形角平分线分对边的比等于邻边之比。", deriv="用面积法或正弦定理。", app="求线段比例。", note="逆定理也成立。", hist="几何定理。", ext="外角平分线也有类似定理。"),
      T("圆的定义", formula="(x-a)^2+(y-b)^2=r^2", explain="平面内到定点距离等于定长的点的集合。", deriv="由距离定义。", app="圆的方程、几何研究。", note="定点是圆心，定长是半径。", hist="最完美的几何图形。", ext="球是圆的三维推广。"),
      T("垂径定理", explain="垂直于弦的直径平分弦且平分弦所对的两条弧。", deriv="由圆的对称性。", app="求弦长、弧长。", note="推论：平分弦（非直径）的直径垂直于弦。", hist="圆的基本定理。", ext="圆是轴对称图形。"),
      T("圆周角定理", formula=r"\text{圆周角}=\frac{1}{2}\text{圆心角}", explain="同弧所对的圆周角等于圆心角的一半。", deriv="分三种情况证明（圆心在角内、边上、外）。", app="求角度。", note="同弧所对圆周角相等。", hist="圆的重要定理。", ext="直径所对圆周角为直角。"),
      T("切线性质", explain="圆的切线垂直于过切点的半径。", deriv="用反证法或极限思想。", app="切线问题。", note="切线与圆只有一个公共点。", hist="圆的切线。", ext="切线长定理：从圆外一点引两条切线长相等。"),
      T("切线判定", explain="经过半径外端且垂直于这条半径的直线是圆的切线。", deriv="切线性质的逆定理。", app="证明切线。", note="判定方法：d=r或垂直半径外端。", hist="切线判定。", ext="切线是割线的极限。"),
      T("圆与圆位置关系", explain="两圆位置关系由圆心距d与半径R,r决定：外离d>R+r，外切d=R+r，相交R-r<d<R+r，内切d=R-r，内含d<R-r。", deriv="由圆心距和半径比较。", app="判断两圆关系。", note="相切时切点在连心线上。", hist="圆与圆关系。", ext="共轴圆系。"),
      T("正多边形", explain="各边相等、各角也相等的多边形。", deriv="由边和角都相等定义。", app="几何计算。", note="正n边形内角=(n-2)·180°/n。", hist="古希腊研究正多边形作图。", ext="正多边形可内接于圆。"),
      T("圆内接四边形", explain="四个顶点都在同一圆上的四边形。", deriv="由共圆定义。", app="证明四点共圆。", note="对角互补，外角等于内对角。", hist="圆内接四边形。", ext="托勒密定理：对边乘积和等于对角线乘积。"),
      T("圆的切线长定理", formula="PA=PB", explain="从圆外一点引圆的两条切线，切线长相等。", deriv="证明两个直角三角形全等。", app="求切线长。", note="连心线平分两切线夹角。", hist="切线性质。", ext="切线长公式PA=√(PO²-r²)。"),
      T("三角形重心", explain="三角形三条中线的交点。", deriv="三条中线交于一点。", app="三角形中心。", note="重心分中线为2:1（顶点到重心:重心到中点）。", hist="几何中心。", ext="重心坐标为三顶点坐标平均。"),
      T("三角形外心", explain="三角形三边垂直平分线的交点，即外接圆圆心。", deriv="垂直平分线上的点到两端点距离相等。", app="外接圆。", note="外心到三顶点距离相等=外接圆半径R。", hist="三角形五心之一。", ext="直角三角形外心在斜边中点。"),
      T("三角形内心", explain="三角形三条角平分线的交点，即内切圆圆心。", deriv="角平分线上的点到两边距离相等。", app="内切圆。", note="内心到三边距离相等=内切圆半径r。", hist="三角形五心之一。", ext="面积S=r·s（s为半周长）。"),
      T("三角形垂心", explain="三角形三条高的交点。", deriv="三条高交于一点。", app="三角形高线。", note="锐角三角形垂心在内部，钝角在外部，直角在顶点。", hist="三角形五心之一。", ext="垂心与外心、重心共线（欧拉线）。"),
      T("三角形旁心", explain="三角形一个内角平分线与另外两个外角平分线的交点。", deriv="类似内心但用外角平分线。", app="旁切圆。", note="旁心到一边及另两边延长线距离相等。", hist="三角形五心之一。", ext="每个三角形有三个旁心。"),
      T("多边形内角和", formula=r"(n-2)\times 180^\circ", explain="n边形内角和为(n-2)×180°。", deriv="从一个顶点引对角线分成n-2个三角形。", app="求多边形内角。", note="n≥3。", hist="多边形基本公式。", ext="正n边形每个内角=(n-2)·180°/n。"),
      T("多边形外角和", formula=r"360^\circ", explain="任意多边形外角和恒为360°。", deriv="每个内角+相邻外角=180°，总和n·180°-(n-2)·180°=360°。", app="求正多边形外角。", note="与边数无关，恒为360°。", hist="多边形性质。", ext="正n边形每个外角=360°/n。"),
      T("相交弦定理", formula=r"PA\cdot PB=PC\cdot PD", explain="圆内两弦AB,CD交于P，则PA·PB=PC·PD。", deriv="由相似三角形。", app="圆内线段计算。", note="P在圆内时。", hist="圆幂定理之一。", ext="P在圆外时为割线定理。"),
      T("切割线定理", formula=r"PT^2=PA\cdot PB", explain="从圆外一点P引切线PT和割线PAB，则PT²=PA·PB。", deriv="由弦切角定理证相似。", app="圆外线段计算。", note="切线长平方等于割线两段乘积。", hist="圆幂定理。", ext="统一为圆幂定理。"),
    ]},
    {"name":"3.3 立体几何","color":"#0f766e","desc":"空间线面、多面体","topics":[
      T("平面", explain="几何中最基本的概念之一，无限延展、无厚薄。", deriv="由现实抽象。", app="立体几何基础。", note="平面用平行四边形表示，用α,β,γ或字母表示。", hist="欧几里得几何基础。", ext="二维流形。"),
      T("平面基本性质", explain="公理1：直线上两点在平面内则直线在平面内；公理2：不共线三点确定一平面；公理3：两平面有公共点则有过该点的公共直线。", deriv="公理体系。", app="空间推理基础。", note="三个公理是立体几何的基石。", hist="欧几里得公理。", ext="希尔伯特公理体系。"),
      T("空间直线位置关系", explain="空间中两条直线有：平行、相交、异面三种位置关系。", deriv="由是否共面和是否有公共点分类。", app="空间线线关系。", note="异面直线不同在任何一个平面内。", hist="立体几何。", ext="异面直线所成角、距离。"),
      T("异面直线", explain="不同在任何一个平面内的两条直线。", deriv="不平行也不相交。", app="空间线线关系。", note="所成角范围(0°,90°]。", hist="立体几何特有概念。", ext="异面直线的公垂线和距离。"),
      T("线面平行判定", explain="若平面外一条直线与平面内一条直线平行，则该直线与此平面平行。", deriv="反证法。", app="证明线面平行。", note="线线平行⇒线面平行。", hist="立体几何。", ext="线面平行⇒线面无公共点。"),
      T("线面平行性质", explain="若直线与平面平行，过此直线的平面与已知平面相交，则交线与该直线平行。", deriv="由线面平行定义推出。", app="由线面平行证线线平行。", note="线面平行⇒线线平行（交线）。", hist="立体几何。", ext="平行关系的传递。"),
      T("线面垂直判定", explain="若一条直线与平面内两条相交直线都垂直，则该直线垂直于这个平面。", deriv="由两条相交直线确定平面方向。", app="证明线面垂直。", note="必须是两条相交直线。", hist="立体几何。", ext="线面垂直⇒线垂直于面内所有直线。"),
      T("线面垂直性质", explain="若两条直线都垂直于同一平面，则这两条直线平行。", deriv="由线面垂直定义。", app="由线面垂直证线线平行。", note="垂直于同一平面的两直线平行。", hist="立体几何。", ext="平面的法向量。"),
      T("面面平行判定", explain="若一个平面内有两条相交直线都平行于另一个平面，则两平面平行。", deriv="由两条相交直线确定平面。", app="证明面面平行。", note="必须是两条相交直线。", hist="立体几何。", ext="面面平行⇒无公共点。"),
      T("面面平行性质", explain="若两个平行平面同时与第三个平面相交，则交线平行。", deriv="由面面平行定义。", app="由面面平行证线线平行。", note="面面平行⇒交线平行。", hist="立体几何。", ext="夹在平行平面间的平行线段相等。"),
      T("面面垂直判定", explain="若一个平面过另一个平面的一条垂线，则两平面垂直。", deriv="由二面角为直角。", app="证明面面垂直。", note="线面垂直⇒面面垂直。", hist="立体几何。", ext="二面角的平面角为90°。"),
      T("面面垂直性质", explain="若两平面垂直，在一个平面内垂直于交线的直线垂直于另一平面。", deriv="由二面角定义。", app="由面面垂直证线面垂直。", note="关键是垂直于交线。", hist="立体几何。", ext="面面垂直⇒可构造线面垂直。"),
      T("二面角", explain="从一条直线出发的两个半平面组成的图形。", deriv="由两个半平面和棱定义。", app="求两个平面的夹角。", note="二面角大小用其平面角度量，范围[0°,180°]。", hist="立体几何。", ext="二面角的平面角作法。"),
      T("棱柱", formula="V=Sh", explain="有两个面互相平行，其余各面都是四边形，相邻四边形公共边互相平行的多面体。", deriv="由面的特征定义。", app="几何体研究。", note="侧棱平行且相等；体积=底面积×高。", hist="多面体。", ext="直棱柱、正棱柱。"),
      T("棱锥", formula=r"V=\frac{1}{3}Sh", explain="一个面是多边形，其余各面是有公共顶点的三角形的多面体。", deriv="由面的特征定义。", app="几何体研究。", note="体积=1/3×底面积×高。", hist="多面体。", ext="正棱锥各侧面全等。"),
      T("棱台", formula=r"V=\frac{1}{3}h(S+\sqrt{SS'}+S')", explain="用平行于棱锥底面的平面截棱锥，截面与底面间的部分。", deriv="由棱锥截得。", app="几何体研究。", note="体积公式。", hist="多面体。", ext="正棱台各侧面全等等腰梯形。"),
      T("圆柱", formula=r"V=\pi r^2h,\ S_\text{侧}=2\pi rh", explain="以矩形一边为轴旋转一周所得的旋转体。", deriv="由旋转定义。", app="几何体研究。", note="侧面展开是矩形。", hist="旋转体。", ext="圆柱的轴截面是矩形。"),
      T("圆锥", formula=r"V=\frac{1}{3}\pi r^2h,\ S_\text{侧}=\pi rl", explain="以直角三角形一条直角边为轴旋转一周所得旋转体。", deriv="由旋转定义。", app="几何体研究。", note="侧面展开是扇形，母线l=√(r²+h²)。", hist="旋转体。", ext="圆锥轴截面是等腰三角形。"),
      T("球", formula=r"V=\frac{4}{3}\pi R^3,\ S=4\pi R^2", explain="空间中到定点距离等于定长的点的集合（球面）及其内部。", deriv="由距离定义。", app="球体计算。", note="球的截面是圆，过球心的截面是大圆。", hist="最对称的立体。", ext="球的表面积和体积公式。"),
      T("点到平面距离", explain="平面外一点到平面的垂线段长度。", deriv="由垂直定义。", app="求距离。", note="是点到平面的最短距离。", hist="立体几何。", ext="等体积法求距离。"),
      T("线面角", explain="直线与平面所成角是直线与它在平面内射影的夹角。", deriv="由射影定义。", app="求线面夹角。", note="范围[0°,90°]。", hist="立体几何。", ext="线面角的正弦=点到面距离/斜线长。"),
    ]},
    {"name":"3.4 解析平面几何","color":"#c2410c","desc":"直线、圆锥曲线","topics":[
      T("直线斜率", formula=r"k=\frac{y_2-y_1}{x_2-x_1}=\tan\alpha", explain="直线的斜率等于两点纵坐标差除以横坐标差，也等于倾斜角的正切。", deriv="由倾斜角定义。", app="求直线斜率。", note="垂直于x轴的直线斜率不存在。", hist="解析几何。", ext="斜率是直线方向的数量刻画。"),
      T("直线方程点斜式", formula="y-y_1=k(x-x_1)", explain="已知直线上一点(x₁,y₁)和斜率k的直线方程。", deriv="由斜率定义。", app="求直线方程。", note="斜率存在时使用。", hist="直线方程。", ext="斜截式、两点式等。"),
      T("直线方程斜截式", formula="y=kx+b", explain="已知斜率k和y轴截距b的直线方程。", deriv="点斜式的特例（过(0,b)）。", app="求直线方程。", note="b是直线与y轴交点的纵坐标。", hist="直线方程。", ext="斜率不存在时不能用。"),
      T("直线方程两点式", formula=r"\frac{y-y_1}{y_2-y_1}=\frac{x-x_1}{x_2-x_1}", explain="已知两点(x₁,y₁),(x₂,y₂)的直线方程。", deriv="由斜率相等。", app="求直线方程。", note="x₁≠x₂,y₁≠y₂时使用。", hist="直线方程。", ext="可化为一般式。"),
      T("直线方程一般式", formula="Ax+By+C=0", explain="直线的一般方程，A,B不同时为零。", deriv="由各种形式统一。", app="直线方程的统一形式。", note="所有直线都可写成一般式。", hist="直线方程。", ext="法向量为(A,B)。"),
      T("两直线平行", formula=r"k_1=k_2\ (b_1\neq b_2)", explain="两直线平行当且仅当斜率相等且截距不等（斜率存在时）。", deriv="由斜率定义。", app="判断平行。", note="一般式中A₁B₂-A₂B₁=0且不重合。", hist="解析几何。", ext="平行直线无交点。"),
      T("两直线垂直", formula="k_1k_2=-1", explain="两直线垂直当且仅当斜率乘积为-1（斜率存在时）。", deriv="由方向向量点积为零。", app="判断垂直。", note="一条斜率为0，另一条不存在时也垂直。", hist="解析几何。", ext="一般式中A₁A₂+B₁B₂=0。"),
      T("两直线交点", explain="联立两直线方程求解。", deriv="方程组的解即交点。", app="求交点。", note="无解⟺平行；无穷多解⟺重合。", hist="解析几何。", ext="交点坐标是方程组的解。"),
      T("点到直线距离", formula=r"d=\frac{|Ax_0+By_0+C|}{\sqrt{A^2+B^2}}", explain="点(x₀,y₀)到直线Ax+By+C=0的距离。", deriv="由垂线方向向量推导。", app="求点到直线距离。", note="分子绝对值保证非负。", hist="解析几何。", ext="两平行线距离。"),
      T("两平行线距离", formula=r"d=\frac{|C_1-C_2|}{\sqrt{A^2+B^2}}", explain="两平行线Ax+By+C₁=0和Ax+By+C₂=0间的距离。", deriv="转化为点到直线距离。", app="求平行线距离。", note="要求两方程A,B相同。", hist="解析几何。", ext="可在一条线上取点算距离。"),
      T("圆的标准方程", formula="(x-a)^2+(y-b)^2=r^2", explain="以(a,b)为圆心、r为半径的圆的方程。", deriv="由距离公式。", app="圆的方程。", note="圆心(a,b)，半径r。", hist="解析几何。", ext="一般方程x²+y²+Dx+Ey+F=0。"),
      T("圆的一般方程", formula="x^2+y^2+Dx+Ey+F=0", explain="圆的一般方程。", deriv="由标准方程展开。", app="圆的方程。", note="D²+E²-4F>0时表示圆，圆心(-D/2,-E/2)，半径√(D²+E²-4F)/2。", hist="解析几何。", ext="圆的方程的统一形式。"),
      T("直线与圆位置关系", explain="由圆心到直线距离d与半径r比较：d>r相离，d=r相切，d<r相交。", deriv="由距离和半径。", app="判断直线与圆关系。", note="也可联立方程用判别式。", hist="解析几何。", ext="相交时弦长=2√(r²-d²)。"),
      T("椭圆定义", formula="|PF_1|+|PF_2|=2a>2c", explain="平面内到两定点F₁,F₂距离之和为常数(2a>2c)的点的轨迹。", deriv="由距离条件。", app="行星轨道、光学。", note="两定点叫焦点，距离2c叫焦距，2a叫长轴长。", hist="圆锥曲线。", ext="椭圆的光学性质。"),
      T("椭圆标准方程", formula=r"\frac{x^2}{a^2}+\frac{y^2}{b^2}=1\ (a>b>0)", explain="焦点在x轴上的椭圆标准方程。", deriv="由定义推导。", app="椭圆方程。", note="c²=a²-b²；长轴2a，短轴2b。", hist="解析几何。", ext="焦点在y轴上时x²/b²+y²/a²=1。"),
      T("椭圆性质", explain="椭圆关于x轴、y轴、原点对称，顶点(±a,0),(0,±b)，离心率e=c/a∈(0,1)。", deriv="由标准方程分析。", app="椭圆分析。", note="e越接近0越圆，越接近1越扁。", hist="圆锥曲线。", ext="椭圆的准线、焦半径。"),
      T("双曲线定义", formula="||PF_1|-|PF_2||=2a<2c", explain="平面内到两定点距离之差的绝对值为常数(2a<2c)的点的轨迹。", deriv="由距离条件。", app="双曲线轨迹。", note="2a<2c否则无轨迹。", hist="圆锥曲线。", ext="双曲线的光学性质。"),
      T("双曲线标准方程", formula=r"\frac{x^2}{a^2}-\frac{y^2}{b^2}=1", explain="焦点在x轴上的双曲线标准方程。", deriv="由定义推导。", app="双曲线方程。", note="c²=a²+b²；实轴2a，虚轴2b。", hist="解析几何。", ext="渐近线y=±(b/a)x。"),
      T("双曲线渐近线", formula=r"y=\pm\frac{b}{a}x", explain="双曲线无限接近但不相交的直线。", deriv="当x,y→∞时方程近似为x²/a²-y²/b²=0。", app="双曲线分析。", note="是双曲线的重要特征。", hist="圆锥曲线。", ext="等轴双曲线渐近线互相垂直。"),
      T("抛物线定义", formula="|PF|=d", explain="平面内到定点F和定直线l距离相等的点的轨迹。", deriv="由距离相等条件。", app="抛物线轨迹、光学。", note="定点F是焦点，定直线l是准线。", hist="圆锥曲线。", ext="抛物线的光学性质（平行光聚焦）。"),
      T("抛物线标准方程", formula=r"y^2=2px\ (p>0)", explain="顶点在原点、焦点在x轴正半轴的抛物线方程。", deriv="由定义推导。", app="抛物线方程。", note="焦点(p/2,0)，准线x=-p/2。", hist="解析几何。", ext="四种开口方向的标准方程。"),
      T("圆锥曲线统一定义", formula=r"e=\frac{|PF|}{d}", explain="到定点距离与到定直线距离之比为常数e的点的轨迹：e<1椭圆，e=1抛物线，e>1双曲线。", deriv="由离心率统一。", app="统一研究圆锥曲线。", note="e是离心率。", hist="阿波罗尼奥斯圆锥曲线论。", ext="极坐标方程。"),
    ]},
    {"name":"3.5 解析立体几何","color":"#7c3aed","desc":"空间向量、空间方程","topics":[
      T("空间向量", formula=r"\vec{a}=(x,y,z)", explain="空间中的向量，用三维坐标表示。", deriv="由平面向量推广。", app="空间几何计算。", note="运算规则与平面向量类似。", hist="立体几何代数化。", ext="n维向量。"),
      T("空间向量运算", formula=r"(x_1,y_1,z_1)\pm(x_2,y_2,z_2)=(x_1\pm x_2,y_1\pm y_2,z_1\pm z_2)", explain="空间向量加减、数乘、数量积的坐标运算。", deriv="由平面向量推广。", app="空间向量计算。", note="数量积=x₁x₂+y₁y₂+z₁z₂。", hist="向量代数。", ext="推广到n维。"),
      T("空间向量共线", formula=r"\vec{a}=\lambda\vec{b}", explain="空间两向量共线条件。", deriv="与平面类似。", app="判断空间线线平行。", note="b≠0时。", hist="向量代数。", ext="推广到n维。"),
      T("空间向量共面", formula=r"\vec{c}=\lambda\vec{a}+\mu\vec{b}", explain="空间三向量共面条件：存在λ,μ使c=λa+μb。", deriv="由平面向量基本定理推广。", app="判断共面、线面平行。", note="a,b不共线时。", hist="向量代数。", ext="混合积为零。"),
      T("空间向量数量积", formula=r"\vec{a}\cdot\vec{b}=|\vec{a}||\vec{b}|\cos\theta=x_1x_2+y_1y_2+z_1z_2", explain="空间向量的数量积。", deriv="由平面推广。", app="求空间角、证垂直。", note="a⊥b⟺a·b=0。", hist="向量代数。", ext="内积空间。"),
      T("空间向量模", formula=r"|\vec{a}|=\sqrt{x^2+y^2+z^2}", explain="空间向量的模。", deriv="由数量积a·a。", app="求空间距离。", note="即向量长度。", hist="距离公式。", ext="欧氏范数。"),
      T("空间两点距离", formula=r"d=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2+(z_2-z_1)^2}", explain="空间中两点间的距离公式。", deriv="由向量模或勾股定理推广。", app="求空间距离。", note="平面距离公式的推广。", hist="解析几何。", ext="推广到n维。"),
      T("直线方向向量", explain="与直线平行的非零向量。", deriv="由平行定义。", app="确定直线方向。", note="不唯一，可差非零倍数。", hist="解析几何。", ext="直线的方向余弦。"),
      T("空间直线方程", formula=r"\frac{x-x_0}{a}=\frac{y-y_0}{b}=\frac{z-z_0}{c}", explain="过点(x₀,y₀,z₀)方向向量(a,b,c)的直线方程（点向式）。", deriv="由方向向量。", app="空间直线方程。", note="也可写参数方程。", hist="解析几何。", ext="一般式为两平面交线。"),
      T("平面法向量", explain="垂直于平面的非零向量。", deriv="由垂直定义。", app="确定平面方向。", note="不唯一。", hist="解析几何。", ext="平面法向量可由面内两向量叉积得到。"),
      T("空间平面方程", formula="A(x-x_0)+B(y-y_0)+C(z-z_0)=0", explain="过点(x₀,y₀,z₀)法向量(A,B,C)的平面方程。", deriv="由法向量和点法式。", app="空间平面方程。", note="一般式Ax+By+Cz+D=0。", hist="解析几何。", ext="法向量(A,B,C)。"),
      T("线面角向量法", formula=r"\sin\theta=\frac{|\vec{v}\cdot\vec{n}|}{|\vec{v}||\vec{n}|}", explain="用方向向量v和法向量n求线面角θ。", deriv="线面角与方向向量和法向量夹角互余。", app="求线面角。", note="θ∈[0,90°]。", hist="向量法。", ext="避免找角的困难。"),
      T("二面角向量法", formula=r"\cos\theta=\pm\frac{\vec{n_1}\cdot\vec{n_2}}{|\vec{n_1}||\vec{n_2}|}", explain="用法向量求二面角，注意法向量方向选择。", deriv="二面角与法向量夹角相等或互补。", app="求二面角。", note="需判断锐角还是钝角。", hist="向量法。", ext="法向量夹角与二面角的关系。"),
      T("点到平面距离向量法", formula=r"d=\frac{|\vec{AP}\cdot\vec{n}|}{|\vec{n}|}", explain="点A到平面的距离，P是平面上一点，n是法向量。", deriv="由向量投影。", app="求点面距离。", note="AP是从A到平面上一点P的向量。", hist="向量法。", ext="比几何法更简便。"),
      T("异面直线距离向量法", formula=r"d=\frac{|\vec{AB}\cdot\vec{n}|}{|\vec{n}|}", explain="异面直线间距离，A,B分别在两直线上，n是公垂线方向。", deriv="由向量投影。", app="求异面直线距离。", note="n可取两直线方向向量的叉积。", hist="向量法。", ext="公垂线方向n=v₁×v₂。"),
      T("空间直线参数方程", formula=r"\frac{x-x_0}{a}=\frac{y-y_0}{b}=\frac{z-z_0}{c}=t", explain="过点(x₀,y₀,z₀)方向向量(a,b,c)的直线。", deriv="由方向向量参数化。", app="空间直线方程。", note="方向数a,b,c不全为0。", hist="解析几何。", ext="参数式x=x₀+at等。"),
      T("空间平面一般方程", formula="Ax+By+Cz+D=0", explain="空间平面的一般式，法向量(A,B,C)。", deriv="由法向量和点法式展开。", app="平面方程。", note="A²+B²+C²≠0。", hist="解析几何。", ext="截距式x/a+y/b+z/c=1。"),
      T("空间平面截距式", formula=r"\frac{x}{a}+\frac{y}{b}+\frac{z}{c}=1", explain="在x,y,z轴截距分别为a,b,c的平面。", deriv="由一般方程令两坐标为0推导。", app="已知截距求平面。", note="a,b,c均不为0。", hist="解析几何。", ext="便于画图。"),
      T("两平面位置关系", explain="平行、相交（垂直是特例）、重合。", deriv="由法向量关系判断。", app="判断平面关系。", note="法向量平行则平面平行或重合。", hist="空间几何。", ext="二面角由法向量夹角求。"),
      T("直线与平面位置关系", explain="平行、相交（垂直是特例）、在平面内。", deriv="由方向向量与法向量关系判断。", app="判断线面关系。", note="方向向量与法向量垂直则线面平行或在面内。", hist="空间几何。", ext="线面角是方向向量与法向量夹角的余角。"),
      T("球面方程", formula="(x-a)^2+(y-b)^2+(z-c)^2=R^2", explain="球心(a,b,c)半径R的球面。", deriv="由空间两点距离公式。", app="球面方程。", note="一般式x²+y²+z²+Dx+Ey+Fz+G=0。", hist="解析几何。", ext="球的体积和表面积。"),
      T("空间中点到直线距离", explain="点到空间直线的距离。", deriv="用向量叉积：d=|v×PA|/|v|。", app="距离计算。", note="v是直线方向向量，P是直线上一点。", hist="空间几何。", ext="平行直线间距离同理。"),
      T("空间两直线夹角", formula=r"\cos\theta=\frac{|\vec{v_1}\cdot\vec{v_2}|}{|\vec{v_1}||\vec{v_2}|}", explain="两直线方向向量夹角（取锐角）。", deriv="由向量点积。", app="求线线角。", note="取绝对值保证为锐角。", hist="空间几何。", ext="垂直时点积为0。"),
    ]},
  ]},
  {"ch":"第四章","title":"概率与统计","en":"PROBABILITY & STATISTICS","sub":"计数原理 · 排列组合 · 概率 · 统计","desc":"从计数原理到概率统计，构建数据与不确定性的数学体系。","sections":[
    {"name":"4.1 计数原理与排列组合","color":"#2563eb","desc":"分类分步、排列组合","topics":[
      T("分类加法计数原理", formula=r"N=m_1+m_2+\cdots+m_n", explain="完成一件事有n类办法，各类办法数相加得总方法数。", deriv="互斥情形相加。", app="计数问题。", note="各类办法互斥。", hist="计数原理。", ext="加法原理。"),
      T("分步乘法计数原理", formula=r"N=m_1\times m_2\times\cdots\times m_n", explain="完成一件事需n个步骤，各步骤方法数相乘得总方法数。", deriv="独立步骤相乘。", app="计数问题。", note="各步骤相互独立，缺一不可。", hist="计数原理。", ext="乘法原理。"),
      T("排列", formula=r"A_n^m=\frac{n!}{(n-m)!}", explain="从n个不同元素中取m个按一定顺序排成一列。", deriv="第一个位置n种，第二个n-1种，...，第m个n-m+1种。", app="有序选取。", note="0!=1；Aₙⁿ=n!。", hist="组合数学。", ext="可重复排列nᵐ。"),
      T("阶乘", formula=r"n!=n(n-1)\cdots 2\cdot 1", explain="n的阶乘是1到n的连乘积。", deriv="全排列数。", app="排列组合计算。", note="0!=1（约定）。", hist="阶乘概念。", ext="斯特林公式近似n!≈√(2πn)(n/e)ⁿ。"),
      T("组合", formula=r"C_n^m=\frac{A_n^m}{m!}=\frac{n!}{m!(n-m)!}", explain="从n个不同元素中取m个并成一组（不计顺序）。", deriv="排列数除以m!（每组的排列数）。", app="无序选取。", note="Cₙᵐ=Cₙⁿ⁻ᵐ；Cₙ⁰=1。", hist="组合数学。", ext="二项式系数。"),
      T("组合数性质", formula="C_n^m=C_n^{n-m}", explain="组合数的对称性：Cₙᵐ=Cₙⁿ⁻ᵐ。", deriv="取m个等价于留n-m个。", app="简化计算。", note="Cₙᵐ+Cₙᵐ⁻¹=Cₙ₊₁ᵐ（帕斯卡恒等式）。", hist="组合恒等式。", ext="杨辉三角的性质。"),
      T("组合数性质2", formula="C_n^m=C_{n-1}^m+C_{n-1}^{m-1}", explain="帕斯卡恒等式。", deriv="第n个元素取或不取。", app="递推计算组合数。", note="是杨辉三角的生成规律。", hist="帕斯卡1654年系统研究。", ext="二项式定理的系数关系。"),
      T("二项式定理", formula=r"(a+b)^n=\sum_{k=0}^n C_n^k a^{n-k}b^k", explain="(a+b)ⁿ的展开式。", deriv="数学归纳法或组合意义。", app="二项式展开、近似计算。", note="第k+1项Tₖ₊₁=Cₙᵏaⁿ⁻ᵏbᵏ。", hist="牛顿推广到任意指数。", ext="二项分布的概率公式。"),
      T("二项式系数", formula="C_n^k", explain="二项式展开式的系数。", deriv="由组合意义。", app="展开式系数。", note="系数和=2ⁿ；奇数项和=偶数项和=2ⁿ⁻¹。", hist="杨辉三角。", ext="最大系数在中间项。"),
      T("排列组合应用", explain="计数问题的核心：判断有序（排列）还是无序（组合），分类还是分步。", deriv="由计数原理。", app="实际计数问题。", note="先选后排、捆绑法、插空法、隔板法。", hist="组合数学。", ext="复杂计数需灵活运用。"),
      T("捆绑法", explain="要求相邻的元素先捆绑成一个整体再排列。", deriv="处理相邻问题。", app="排队问题（相邻）。", note="捆绑后内部还要排列。", hist="计数技巧。", ext="与插空法对偶。"),
      T("插空法", explain="要求不相邻的元素先排其他元素，再插入空隙。", deriv="处理不相邻问题。", app="排队问题（不相邻）。", note="n个元素有n+1个空隙。", hist="计数技巧。", ext="与捆绑法对偶。"),
      T("隔板法", formula="C_{n-1}^{m-1}", explain="将n个相同元素分给m个人（每人至少1个）的方法数。", deriv="n个元素间有n-1个空隙，插m-1个隔板。", app="分配问题。", note="要求元素相同且每人至少1个。", hist="计数技巧。", ext="允许0个时转化为n+m-1个元素插m-1个隔板。"),
      T("圆排列", formula=r"A_n=\frac{(n-1)!}{1}", explain="n个人围圆桌坐的方法数。", deriv="固定一人后其余n-1人排列。", app="圆桌座位安排。", note="圆排列数=(n-1)!。", hist="组合数学。", ext="项链排列除以2（翻转相同）。"),
      T("可重复排列", formula="n^m", explain="从n个不同元素中可重复取m个的排列数。", deriv="每个位置n种选择，共m个位置。", app="密码、编码。", note="允许重复选取。", hist="组合数学。", ext="与不可重复排列的区别。"),
      T("错位排列", formula=r"D_n=n!\sum_{k=0}^n\frac{(-1)^k}{k!}", explain="n封信全部装错信封的方法数。", deriv="容斥原理：总数减去至少一封正确。", app="信封问题、排列组合。", note="D₄=9，D₅=44。", hist="蒙莫尔问题。", ext="Dₙ/n!→1/e。"),
      T("多重集排列", formula=r"\frac{n!}{n_1!n_2!\cdots n_k!}", explain="n个元素中有重复（n₁个相同，n₂个相同，...）的全排列数。", deriv="总数n!除以各组内部排列。", app="重复元素排列。", note="分母是各组重复数的阶乘。", hist="组合数学。", ext="多项式定理的系数。"),
            T("容斥原理", formula=r"|A_1\cup A_2|=|A_1|+|A_2|-|A_1\cap A_2|", explain="两个集合的容斥: 并集=两集合和减交集。", deriv="加多了交集要减去。", app="计数重叠元素。", note="三集合公式需加减交替。", hist="组合计数基本原理。", ext="n个集合的容斥公式。"),
      T("鸽巢原理", explain="n+1个物品放入n个盒子，至少有一个盒子有2个以上物品。", deriv="反证法：若每个盒子最多1个，总数最多n，矛盾。", app="存在性证明。", note="推广：kn+1个物品放入n个盒子，至少一盒k+1个。", hist="狄利克雷原理。", ext="拉姆齐理论的基础。"),
    ]},
    {"name":"4.2 概率","color":"#7c3aed","desc":"古典、几何、条件概率","topics":[
      T("随机事件", explain="在一定条件下可能发生也可能不发生的事件。", deriv="由随机性定义。", app="描述不确定现象。", note="必然事件概率1，不可能事件概率0。", hist="概率论基础。", ext="样本空间与事件域。"),
      T("概率定义", formula=r"P(A)=\frac{m}{n}", explain="古典概型中事件A的概率等于A包含的基本事件数m除以总基本事件数n。", deriv="等可能性假设。", app="古典概率计算。", note="要求基本事件等可能且有限。", hist="概率的古典定义。", ext="几何概型、公理化定义。"),
      T("概率基本性质", formula=r"0\leq P(A)\leq 1", explain="概率取值在[0,1]之间。", deriv="由频率性质。", app="概率估计。", note="P(Ω)=1，P(∅)=0。", hist="概率论公理。", ext="可列可加性。"),
      T("互斥事件", formula=r"P(A\cup B)=P(A)+P(B)", explain="互斥事件（不能同时发生）的和事件概率等于概率之和。", deriv="由互斥性。", app="概率计算。", note="互斥即A∩B=∅。", hist="概率加法。", ext="一般情形P(A∪B)=P(A)+P(B)-P(A∩B)。"),
      T("对立事件", formula=r"P(\bar{A})=1-P(A)", explain="对立事件概率之和为1。", deriv="由对立定义。", app="简化概率计算。", note="A与Ā互斥且A∪Ā=Ω。", hist="概率性质。", ext="补事件。"),
      T("古典概型", explain="试验结果有限且等可能的概率模型。", deriv="有限性+等可能性。", app="掷骰子、摸球等。", note="用计数原理求m和n。", hist="概率论早期模型。", ext="几何概型推广到无限情形。"),
      T("几何概型", formula=r"P(A)=\frac{\text{构成A的区域度量}}{\text{全体结果的区域度量}}", explain="试验结果无限且等可能的概率模型。", deriv="由等可能性和测度。", app="约会问题、投针问题。", note="用长度、面积、体积度量。", hist="概率论推广。", ext="蒙特卡洛方法。"),
      T("条件概率", formula=r"P(A|B)=\frac{P(AB)}{P(B)}", explain="在事件B发生的条件下A发生的概率。", deriv="由条件概率定义。", app="依赖事件的概率。", note="要求P(B)>0。", hist="条件概率。", ext="P(A|B)≠P(A)说明A,B不独立。"),
      T("事件独立性", formula="P(AB)=P(A)P(B)", explain="事件A,B独立当且仅当P(AB)=P(A)P(B)。", deriv="由独立性定义。", app="独立事件概率。", note="独立⟺P(A|B)=P(A)（P(B)>0时）。", hist="独立概念。", ext="推广到n个事件独立。"),
      T("独立重复试验", formula="P(X=k)=C_n^k p^k(1-p)^{n-k}", explain="n次独立重复试验中事件A发生k次的概率（二项分布）。", deriv="由独立性和互斥性。", app="伯努利试验。", note="每次试验A发生概率为p。", hist="二项分布。", ext="n很大p很小时近似泊松分布。"),
      T("全概率公式", formula=r"P(A)=\sum P(B_i)P(A|B_i)", explain="若B₁,B₂,...,Bₙ是完备事件组，则P(A)=ΣP(Bᵢ)P(A|Bᵢ)。", deriv="由互斥分解和条件概率。", app="复杂事件概率。", note="完备事件组：互斥且并为Ω。", hist="概率公式。", ext="贝叶斯公式的基础。"),
      T("贝叶斯公式", formula=r"P(B_i|A)=\frac{P(B_i)P(A|B_i)}{\sum P(B_j)P(A|B_j)}", explain="已知结果A求原因Bᵢ的概率。", deriv="由条件概率和全概率公式。", app="逆概率、诊断。", note="P(Bᵢ)是先验概率，P(Bᵢ|A)是后验概率。", hist="贝叶斯1763年发表。", ext="贝叶斯统计的基础。"),
      T("随机变量", explain="将随机试验结果数量化的变量。", deriv="样本空间到实数的映射。", app="用数学方法研究随机现象。", note="分离散型和连续型。", hist="概率论现代化。", ext="随机变量的分布函数。"),
      T("离散型随机变量", explain="取值为有限或可列个的随机变量。", deriv="由取值特征分类。", app="计数型随机现象。", note="用分布列描述。", hist="概率论。", ext="二项分布、泊松分布、超几何分布。"),
      T("分布列", formula="P(X=x_i)=p_i", explain="离散型随机变量X取各值的概率。", deriv="由概率定义。", app="描述离散型随机变量。", note="Σpᵢ=1，pᵢ≥0。", hist="概率论。", ext="分布列即概率质量函数。"),
      T("数学期望", formula=r"E(X)=\sum x_i p_i", explain="离散型随机变量的期望值（加权平均）。", deriv="由概率加权平均。", app="预测平均结果。", note="E(aX+b)=aE(X)+b。", hist="概率论。", ext="连续型用积分。"),
      T("方差", formula=r"D(X)=\sum(x_i-E(X))^2 p_i", explain="随机变量取值的离散程度。", deriv="由偏离期望的平方的期望。", app="衡量波动大小。", note="D(aX+b)=a²D(X)；标准差=√D(X)。", hist="概率论。", ext="方差小说明取值集中。"),
      T("期望线性性质", formula="E(X+Y)=E(X)+E(Y)", explain="两个随机变量和的期望等于期望之和。", deriv="由期望定义和加法交换律。", app="期望计算。", note="无需X,Y独立。", hist="期望性质。", ext="E(aX+bY)=aE(X)+bE(Y)。"),
      T("独立随机变量方差", formula="D(X+Y)=D(X)+D(Y)", explain="独立随机变量和的方差等于方差之和。", deriv="由独立性消去协方差项。", app="方差计算。", note="要求X,Y独立。", hist="方差性质。", ext="不独立时D(X+Y)=D(X)+D(Y)+2Cov(X,Y)。"),
      T("协方差", formula="Cov(X,Y)=E[(X-E(X))(Y-E(Y))]", explain="衡量两个随机变量的协同变化程度。", deriv="由期望定义。", app="相关性分析。", note="Cov(X,Y)=E(XY)-E(X)E(Y)。", hist="概率论。", ext="独立⟹协方差为0，反之不一定。"),
      T("相关系数", formula=r"\rho=\frac{Cov(X,Y)}{\sqrt{D(X)D(Y)}}", explain="标准化的协方差，衡量线性相关程度。", deriv="由协方差和标准差。", app="相关性分析。", note="|ρ|≤1，ρ=±1时完全线性相关。", hist="概率论。", ext="ρ=0称不相关（不一定独立）。"),
      T("几何概型约会问题", explain="两人在约定时间段内到达，求能相遇的概率。", deriv="用面积比计算。", app="几何概型经典问题。", note="设到达时间为x,y，|x-y|≤t时相遇。", hist="概率论经典。", ext="几何概型的典型应用。"),
      T("条件概率性质", formula=r"P(A|B)=\frac{P(AB)}{P(B)}", explain="条件概率满足概率的所有性质。", deriv="由条件概率定义。", app="依赖事件。", note="P(Ω|B)=1，P(∅|B)=0。", hist="条件概率。", ext="条件概率也是概率测度。"),
      T("全概率公式应用", explain="将复杂事件分解为互斥情形分别计算。", deriv="由完备事件组。", app="分层抽样概率。", note="关键是找到合适的完备事件组。", hist="概率公式。", ext="与贝叶斯公式配合使用。"),
      T("贝叶斯公式应用", explain="已知结果反推原因的概率。", deriv="由条件概率和全概率。", app="医学诊断、垃圾邮件过滤。", note="先验概率更新为后验概率。", hist="贝叶斯推断。", ext="机器学习中的朴素贝叶斯。"),
    ]},
    {"name":"4.3 统计","color":"#0f766e","desc":"抽样、分布、估计","topics":[
      T("总体与样本", explain="研究对象的全体叫总体，从中抽取的部分叫样本。", deriv="由统计研究范围。", app="抽样调查。", note="样本容量是样本中个体数。", hist="统计学基础。", ext="抽样方法。"),
      T("简单随机抽样", explain="从总体中逐个不放回抽取，每个个体被抽到的机会相等。", deriv="等可能性。", app="简单抽样。", note="抽签法、随机数表法。", hist="抽样方法。", ext="系统抽样、分层抽样。"),
      T("系统抽样", explain="将总体分成均衡的若干部分，按规则从每部分抽取。", deriv="等距抽样。", app="大总体抽样。", note="先编号，再等距抽取。", hist="抽样方法。", ext="当总体有周期时要注意。"),
      T("分层抽样", explain="将总体分成互不交叉的层，按比例从各层抽取。", deriv="按层比例。", app="总体差异大时抽样。", note="各层独立抽取，样本与总体结构相似。", hist="抽样方法。", ext="比例分配、最优分配。"),
      T("频率分布表", explain="将数据分组，统计各组频数和频率的表格。", deriv="由数据整理。", app="数据分布分析。", note="频率=频数/总数。", hist="描述统计。", ext="频率分布直方图。"),
      T("频率分布直方图", explain="用矩形面积表示频率的统计图。", deriv="由频率分布表绘制。", app="直观展示数据分布。", note="纵轴是频率/组距，面积=频率。", hist="数据可视化。", ext="密度曲线的近似。"),
      T("众数", explain="出现次数最多的数据值。", deriv="由频率最高。", app="数据集中趋势。", note="可能有多个众数或没有。", hist="统计量。", ext="直方图中最高矩形中点。"),
      T("中位数", explain="将数据从小到大排列后位于中间的数值。", deriv="由位置定义。", app="数据集中趋势。", note="n奇取中间，n偶取中间两数平均。", hist="统计量。", ext="不受极端值影响。"),
      T("平均数", formula=r"\bar{x}=\frac{1}{n}\sum x_i", explain="所有数据之和除以数据个数。", deriv="由平均定义。", app="数据集中趋势。", note="加权平均可按频率加权。", hist="统计量。", ext="受极端值影响大。"),
      T("标准差", formula=r"s=\sqrt{\frac{1}{n}\sum(x_i-\bar{x})^2}", explain="方差的算术平方根。", deriv="由方差开方。", app="衡量数据波动（与原数据同单位）。", note="与原数据单位一致。", hist="统计量。", ext="方差的平方根。"),
      T("线性相关", explain="两个变量的散点图大致分布在一条直线附近。", deriv="由散点图形态。", app="回归分析基础。", note="正相关/负相关/不相关。", hist="相关分析。", ext="相关系数r衡量相关程度。"),
      T("线性回归方程", formula=r"\hat{y}=\hat{b}x+\hat{a}", explain="用最小二乘法拟合的直线方程。", deriv="使残差平方和最小。", app="预测。", note="回归直线过样本中心点(x̄,ȳ)。", hist="高尔顿提出回归概念。", ext="最小二乘法。"),
      T("最小二乘法", explain="通过最小化残差平方和估计参数。", deriv="对残差平方和求导令其为零。", app="参数估计。", note="是线性回归的核心方法。", hist="高斯、勒让德独立提出。", ext="推广到非线性和多元回归。"),
      T("独立性检验", explain="检验两个分类变量是否有关联。", deriv="卡方检验。", app="列联表分析。", note="构造K²统计量与临界值比较。", hist="假设检验。", ext="卡方分布。"),
      T("正态分布", formula=r"f(x)=\frac{1}{\sqrt{2\pi}\sigma}e^{-\frac{(x-\mu)^2}{2\sigma^2}}", explain="最重要的连续型概率分布，钟形曲线。", deriv="由中心极限定理。", app="自然和社会现象广泛适用。", note="N(μ,σ²)，μ是期望，σ是标准差。", hist="棣莫弗-拉普拉斯。", ext="3σ原则：P(μ-3σ<X<μ+3σ)≈99.7%。"),
      T("正态分布性质", explain="关于x=μ对称，在μ处取最大值，σ越小越集中。", deriv="由密度函数分析。", app="质量控制、误差分析。", note="P(μ-σ<X<μ+σ)≈68.3%。", hist="正态分布。", ext="标准化Z=(X-μ)/σ~N(0,1)。"),
      T("标准正态分布", formula=r"Z=\frac{X-\mu}{\sigma}\sim N(0,1)", explain="均值为0、标准差为1的正态分布。", deriv="对一般正态变量标准化。", app="查标准正态分布表求概率。", note="Φ(z)表示标准正态分布函数。", hist="正态分布标准化。", ext="一般正态概率转化为标准正态查表。"),
      T("3σ原则", formula=r"P(\mu-3\sigma<X<\mu+3\sigma)\approx 99.7\%", explain="正态变量落在(μ-3σ,μ+3σ)内的概率约99.7%。", deriv="由正态分布密度积分。", app="质量控制（异常值判定）。", note="几乎所有数据都在3σ范围内。", hist="统计过程控制。", ext="6σ管理法源于此。"),
      T("二项分布", formula=r"X\sim B(n,p),\ P(X=k)=C_n^k p^k(1-p)^{n-k}", explain="n次独立伯努利试验中成功次数的分布。", deriv="由独立重复试验。", app="产品检验、抽样。", note="E(X)=np，D(X)=np(1-p)。", hist="伯努利。", ext="n大p小时近似泊松分布。"),
      T("超几何分布", explain="N件产品中有M件次品，抽n件中次品数的分布。", deriv="由古典概型。", app="不放回抽样。", note="与二项分布的区别是不放回。", hist="抽样分布。", ext="N很大时近似二项分布。"),
      T("几何分布", formula="P(X=k)=(1-p)^{k-1}p", explain="首次成功所需试验次数的分布。", deriv="前k-1次失败第k次成功。", app="等待时间。", note="无记忆性。", hist="离散分布。", ext="E(X)=1/p。"),
      T("泊松分布", formula=r"P(X=k)=\frac{\lambda^k e^{-\lambda}}{k!}", explain="稀有事件发生次数的分布。", deriv="二项分布n→∞,np=λ的极限。", app="电话呼叫、粒子衰变。", note="E(X)=D(X)=λ。", hist="泊松1837年提出。", ext="泊松过程的基础。"),
      T("抽样分布", explain="样本统计量的概率分布。", deriv="由抽样过程。", app="统计推断基础。", note="样本均值、样本方差的分布。", hist="推断统计。", ext="t分布、卡方分布、F分布。"),
      T("样本均值分布", formula=r"\bar{X}\sim N(\mu,\frac{\sigma^2}{n})", explain="当总体正态时，样本均值服从正态分布。", deriv="由正态分布的可加性。", app="均值估计。", note="标准误=σ/√n。", hist="中心极限定理。", ext="总体非正态时大样本也近似正态。"),
      T("中心极限定理", explain="大量独立同分布随机变量之和近似服从正态分布。", deriv="概率论基本定理。", app="解释为何很多自然现象服从正态分布。", note="无需总体分布正态，只需n足够大。", hist="棣莫弗-拉普拉斯、林德伯格-莱维。", ext="统计学的基石。"),
      T("参数估计", explain="由样本统计量估计总体参数。", deriv="点估计和区间估计。", app="统计推断。", note="点估计给一个值，区间估计给一个范围。", hist="推断统计。", ext="矩估计、最大似然估计。"),
      T("假设检验", explain="根据样本判断关于总体的假设是否成立。", deriv="小概率原理。", app="科学决策。", note="原假设H₀和备择假设H₁。", hist="内曼-皮尔逊。", ext="第一类错误（弃真）和第二类错误（取伪）。"),
      T("方差分析", explain="检验多个总体均值是否相等的统计方法。", deriv="分解总变异为组间和组内。", app="多组比较。", note="F检验。", hist="费希尔提出。", ext="单因素、双因素方差分析。"),
      T("线性相关关系", explain="两个变量之间的线性依存关系。", deriv="由散点图观察。", app="变量关系分析。", note="相关不代表因果。", hist="统计推断。", ext="用相关系数r度量。"),
      T("相关系数r", formula=r"r=\frac{\sum(x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum(x_i-\bar{x})^2\sum(y_i-\bar{y})^2}}", explain="衡量两个变量线性相关程度的量。", deriv="标准化后的协方差。", app="相关性检验。", note="|r|≤1，|r|越接近1线性相关越强。", hist="皮尔逊提出。", ext="r=0只表示无线性相关，可能有非线性关系。"),
      T("回归分析应用", explain="利用回归方程进行预测和控制。", deriv="由回归方程。", app="经济预测、工程。", note="外推要谨慎。", hist="应用统计。", ext="残差分析检验模型。"),
      T("卡方检验", formula=r"\chi^2=\sum\frac{(f_o-f_e)^2}{f_e}", explain="观测频数与期望频数差异的统计量。", deriv="由皮尔逊提出。", app="拟合优度、独立性检验。", note="自由度影响临界值。", hist="皮尔逊1900年。", ext="卡方分布表。"),
      T("统计决策", explain="基于数据做出决策的过程。", deriv="假设检验、区间估计。", app="质量管理、A/B测试。", note="权衡两类错误。", hist="决策理论。", ext="贝叶斯决策。"),
    ]},
  ]},
]

print("elementary_math_content loaded")